// Code generated by ent, DO NOT EDIT.

package wikipageversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/agurrrrr/shepherd/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldLTE(FieldID, id))
}

// PageSlug applies equality check predicate on the "page_slug" field. It's identical to PageSlugEQ.
func PageSlug(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEQ(FieldPageSlug, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEQ(FieldContent, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEQ(FieldSummary, v))
}

// Author applies equality check predicate on the "author" field. It's identical to AuthorEQ.
func Author(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEQ(FieldAuthor, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// PageSlugEQ applies the EQ predicate on the "page_slug" field.
func PageSlugEQ(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEQ(FieldPageSlug, v))
}

// PageSlugNEQ applies the NEQ predicate on the "page_slug" field.
func PageSlugNEQ(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldNEQ(FieldPageSlug, v))
}

// PageSlugIn applies the In predicate on the "page_slug" field.
func PageSlugIn(vs ...string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldIn(FieldPageSlug, vs...))
}

// PageSlugNotIn applies the NotIn predicate on the "page_slug" field.
func PageSlugNotIn(vs ...string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldNotIn(FieldPageSlug, vs...))
}

// PageSlugGT applies the GT predicate on the "page_slug" field.
func PageSlugGT(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldGT(FieldPageSlug, v))
}

// PageSlugGTE applies the GTE predicate on the "page_slug" field.
func PageSlugGTE(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldGTE(FieldPageSlug, v))
}

// PageSlugLT applies the LT predicate on the "page_slug" field.
func PageSlugLT(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldLT(FieldPageSlug, v))
}

// PageSlugLTE applies the LTE predicate on the "page_slug" field.
func PageSlugLTE(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldLTE(FieldPageSlug, v))
}

// PageSlugContains applies the Contains predicate on the "page_slug" field.
func PageSlugContains(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldContains(FieldPageSlug, v))
}

// PageSlugHasPrefix applies the HasPrefix predicate on the "page_slug" field.
func PageSlugHasPrefix(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldHasPrefix(FieldPageSlug, v))
}

// PageSlugHasSuffix applies the HasSuffix predicate on the "page_slug" field.
func PageSlugHasSuffix(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldHasSuffix(FieldPageSlug, v))
}

// PageSlugEqualFold applies the EqualFold predicate on the "page_slug" field.
func PageSlugEqualFold(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEqualFold(FieldPageSlug, v))
}

// PageSlugContainsFold applies the ContainsFold predicate on the "page_slug" field.
func PageSlugContainsFold(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldContainsFold(FieldPageSlug, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldContainsFold(FieldContent, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldContainsFold(FieldSummary, v))
}

// AuthorEQ applies the EQ predicate on the "author" field.
func AuthorEQ(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEQ(FieldAuthor, v))
}

// AuthorNEQ applies the NEQ predicate on the "author" field.
func AuthorNEQ(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldNEQ(FieldAuthor, v))
}

// AuthorIn applies the In predicate on the "author" field.
func AuthorIn(vs ...string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldIn(FieldAuthor, vs...))
}

// AuthorNotIn applies the NotIn predicate on the "author" field.
func AuthorNotIn(vs ...string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldNotIn(FieldAuthor, vs...))
}

// AuthorGT applies the GT predicate on the "author" field.
func AuthorGT(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldGT(FieldAuthor, v))
}

// AuthorGTE applies the GTE predicate on the "author" field.
func AuthorGTE(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldGTE(FieldAuthor, v))
}

// AuthorLT applies the LT predicate on the "author" field.
func AuthorLT(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldLT(FieldAuthor, v))
}

// AuthorLTE applies the LTE predicate on the "author" field.
func AuthorLTE(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldLTE(FieldAuthor, v))
}

// AuthorContains applies the Contains predicate on the "author" field.
func AuthorContains(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldContains(FieldAuthor, v))
}

// AuthorHasPrefix applies the HasPrefix predicate on the "author" field.
func AuthorHasPrefix(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldHasPrefix(FieldAuthor, v))
}

// AuthorHasSuffix applies the HasSuffix predicate on the "author" field.
func AuthorHasSuffix(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldHasSuffix(FieldAuthor, v))
}

// AuthorEqualFold applies the EqualFold predicate on the "author" field.
func AuthorEqualFold(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEqualFold(FieldAuthor, v))
}

// AuthorContainsFold applies the ContainsFold predicate on the "author" field.
func AuthorContainsFold(v string) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldContainsFold(FieldAuthor, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.WikiPageVersion {
	return predicate.WikiPageVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WikiPageVersion) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WikiPageVersion) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WikiPageVersion) predicate.WikiPageVersion {
	return predicate.WikiPageVersion(sql.NotPredicates(p))
}
