// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BrowserSessionsColumns holds the columns for the "browser_sessions" table.
	BrowserSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_data_dir", Type: field.TypeString},
		{Name: "headless", Type: field.TypeBool, Default: true},
		{Name: "proxy", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "sheep_browser_session", Type: field.TypeInt, Unique: true},
	}
	// BrowserSessionsTable holds the schema information for the "browser_sessions" table.
	BrowserSessionsTable = &schema.Table{
		Name:       "browser_sessions",
		Columns:    BrowserSessionsColumns,
		PrimaryKey: []*schema.Column{BrowserSessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "browser_sessions_sheep_browser_session",
				Columns:    []*schema.Column{BrowserSessionsColumns[6]},
				RefColumns: []*schema.Column{SheepColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "path", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
	}
	// SchedulesColumns holds the columns for the "schedules" table.
	SchedulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "prompt", Type: field.TypeString, Size: 2147483647},
		{Name: "schedule_type", Type: field.TypeEnum, Enums: []string{"cron", "interval"}},
		{Name: "cron_expr", Type: field.TypeString, Nullable: true},
		{Name: "interval_seconds", Type: field.TypeInt, Nullable: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "last_run", Type: field.TypeTime, Nullable: true},
		{Name: "next_run", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "project_schedules", Type: field.TypeInt},
	}
	// SchedulesTable holds the schema information for the "schedules" table.
	SchedulesTable = &schema.Table{
		Name:       "schedules",
		Columns:    SchedulesColumns,
		PrimaryKey: []*schema.Column{SchedulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "schedules_projects_schedules",
				Columns:    []*schema.Column{SchedulesColumns[11]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SheepColumns holds the columns for the "sheep" table.
	SheepColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"idle", "working", "error"}, Default: "idle"},
		{Name: "session_id", Type: field.TypeString, Nullable: true},
		{Name: "provider", Type: field.TypeEnum, Enums: []string{"claude", "opencode", "auto"}, Default: "claude"},
		{Name: "consecutive_failures", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "project_sheep", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// SheepTable holds the schema information for the "sheep" table.
	SheepTable = &schema.Table{
		Name:       "sheep",
		Columns:    SheepColumns,
		PrimaryKey: []*schema.Column{SheepColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sheep_projects_sheep",
				Columns:    []*schema.Column{SheepColumns[8]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SheepNamesColumns holds the columns for the "sheep_names" table.
	SheepNamesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SheepNamesTable holds the schema information for the "sheep_names" table.
	SheepNamesTable = &schema.Table{
		Name:       "sheep_names",
		Columns:    SheepNamesColumns,
		PrimaryKey: []*schema.Column{SheepNamesColumns[0]},
	}
	// SkillsColumns holds the columns for the "skills" table.
	SkillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "scope", Type: field.TypeEnum, Enums: []string{"global", "project"}, Default: "project"},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "bundled", Type: field.TypeBool, Default: false},
		{Name: "effort", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "max_turns", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "disallowed_tools", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "project_skills", Type: field.TypeInt, Nullable: true},
	}
	// SkillsTable holds the schema information for the "skills" table.
	SkillsTable = &schema.Table{
		Name:       "skills",
		Columns:    SkillsColumns,
		PrimaryKey: []*schema.Column{SkillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "skills_projects_skills",
				Columns:    []*schema.Column{SkillsColumns[13]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "prompt", Type: field.TypeString, Size: 2147483647},
		{Name: "summary", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "files_modified", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "completed", "failed", "stopped"}, Default: "pending"},
		{Name: "error", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "output", Type: field.TypeJSON, Nullable: true},
		{Name: "cost_usd", Type: field.TypeFloat64, Nullable: true, Default: 0},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "project_tasks", Type: field.TypeInt, Nullable: true},
		{Name: "sheep_tasks", Type: field.TypeInt, Nullable: true},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tasks_projects_tasks",
				Columns:    []*schema.Column{TasksColumns[11]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "tasks_sheep_tasks",
				Columns:    []*schema.Column{TasksColumns[12]},
				RefColumns: []*schema.Column{SheepColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BrowserSessionsTable,
		ProjectsTable,
		SchedulesTable,
		SheepTable,
		SheepNamesTable,
		SkillsTable,
		TasksTable,
	}
)

func init() {
	BrowserSessionsTable.ForeignKeys[0].RefTable = SheepTable
	SchedulesTable.ForeignKeys[0].RefTable = ProjectsTable
	SheepTable.ForeignKeys[0].RefTable = ProjectsTable
	SkillsTable.ForeignKeys[0].RefTable = ProjectsTable
	TasksTable.ForeignKeys[0].RefTable = ProjectsTable
	TasksTable.ForeignKeys[1].RefTable = SheepTable
}
