// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agurrrrr/shepherd/ent/browsersession"
	"github.com/agurrrrr/shepherd/ent/sheep"
)

// BrowserSessionCreate is the builder for creating a BrowserSession entity.
type BrowserSessionCreate struct {
	config
	mutation *BrowserSessionMutation
	hooks    []Hook
}

// SetUserDataDir sets the "user_data_dir" field.
func (_c *BrowserSessionCreate) SetUserDataDir(v string) *BrowserSessionCreate {
	_c.mutation.SetUserDataDir(v)
	return _c
}

// SetHeadless sets the "headless" field.
func (_c *BrowserSessionCreate) SetHeadless(v bool) *BrowserSessionCreate {
	_c.mutation.SetHeadless(v)
	return _c
}

// SetNillableHeadless sets the "headless" field if the given value is not nil.
func (_c *BrowserSessionCreate) SetNillableHeadless(v *bool) *BrowserSessionCreate {
	if v != nil {
		_c.SetHeadless(*v)
	}
	return _c
}

// SetProxy sets the "proxy" field.
func (_c *BrowserSessionCreate) SetProxy(v string) *BrowserSessionCreate {
	_c.mutation.SetProxy(v)
	return _c
}

// SetNillableProxy sets the "proxy" field if the given value is not nil.
func (_c *BrowserSessionCreate) SetNillableProxy(v *string) *BrowserSessionCreate {
	if v != nil {
		_c.SetProxy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BrowserSessionCreate) SetCreatedAt(v time.Time) *BrowserSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BrowserSessionCreate) SetNillableCreatedAt(v *time.Time) *BrowserSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BrowserSessionCreate) SetUpdatedAt(v time.Time) *BrowserSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BrowserSessionCreate) SetNillableUpdatedAt(v *time.Time) *BrowserSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSheepID sets the "sheep" edge to the Sheep entity by ID.
func (_c *BrowserSessionCreate) SetSheepID(id int) *BrowserSessionCreate {
	_c.mutation.SetSheepID(id)
	return _c
}

// SetSheep sets the "sheep" edge to the Sheep entity.
func (_c *BrowserSessionCreate) SetSheep(v *Sheep) *BrowserSessionCreate {
	return _c.SetSheepID(v.ID)
}

// Mutation returns the BrowserSessionMutation object of the builder.
func (_c *BrowserSessionCreate) Mutation() *BrowserSessionMutation {
	return _c.mutation
}

// Save creates the BrowserSession in the database.
func (_c *BrowserSessionCreate) Save(ctx context.Context) (*BrowserSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BrowserSessionCreate) SaveX(ctx context.Context) *BrowserSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BrowserSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BrowserSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BrowserSessionCreate) defaults() {
	if _, ok := _c.mutation.Headless(); !ok {
		v := browsersession.DefaultHeadless
		_c.mutation.SetHeadless(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := browsersession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := browsersession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BrowserSessionCreate) check() error {
	if _, ok := _c.mutation.UserDataDir(); !ok {
		return &ValidationError{Name: "user_data_dir", err: errors.New(`ent: missing required field "BrowserSession.user_data_dir"`)}
	}
	if v, ok := _c.mutation.UserDataDir(); ok {
		if err := browsersession.UserDataDirValidator(v); err != nil {
			return &ValidationError{Name: "user_data_dir", err: fmt.Errorf(`ent: validator failed for field "BrowserSession.user_data_dir": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Headless(); !ok {
		return &ValidationError{Name: "headless", err: errors.New(`ent: missing required field "BrowserSession.headless"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BrowserSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BrowserSession.updated_at"`)}
	}
	if len(_c.mutation.SheepIDs()) == 0 {
		return &ValidationError{Name: "sheep", err: errors.New(`ent: missing required edge "BrowserSession.sheep"`)}
	}
	return nil
}

func (_c *BrowserSessionCreate) sqlSave(ctx context.Context) (*BrowserSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BrowserSessionCreate) createSpec() (*BrowserSession, *sqlgraph.CreateSpec) {
	var (
		_node = &BrowserSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(browsersession.Table, sqlgraph.NewFieldSpec(browsersession.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserDataDir(); ok {
		_spec.SetField(browsersession.FieldUserDataDir, field.TypeString, value)
		_node.UserDataDir = value
	}
	if value, ok := _c.mutation.Headless(); ok {
		_spec.SetField(browsersession.FieldHeadless, field.TypeBool, value)
		_node.Headless = value
	}
	if value, ok := _c.mutation.Proxy(); ok {
		_spec.SetField(browsersession.FieldProxy, field.TypeString, value)
		_node.Proxy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(browsersession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(browsersession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SheepIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   browsersession.SheepTable,
			Columns: []string{browsersession.SheepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sheep.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.sheep_browser_session = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BrowserSessionCreateBulk is the builder for creating many BrowserSession entities in bulk.
type BrowserSessionCreateBulk struct {
	config
	err      error
	builders []*BrowserSessionCreate
}

// Save creates the BrowserSession entities in the database.
func (_c *BrowserSessionCreateBulk) Save(ctx context.Context) ([]*BrowserSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BrowserSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BrowserSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BrowserSessionCreateBulk) SaveX(ctx context.Context) []*BrowserSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BrowserSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BrowserSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
