// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agurrrrr/shepherd/ent/browsersession"
	"github.com/agurrrrr/shepherd/ent/predicate"
	"github.com/agurrrrr/shepherd/ent/sheep"
)

// BrowserSessionUpdate is the builder for updating BrowserSession entities.
type BrowserSessionUpdate struct {
	config
	hooks    []Hook
	mutation *BrowserSessionMutation
}

// Where appends a list predicates to the BrowserSessionUpdate builder.
func (_u *BrowserSessionUpdate) Where(ps ...predicate.BrowserSession) *BrowserSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserDataDir sets the "user_data_dir" field.
func (_u *BrowserSessionUpdate) SetUserDataDir(v string) *BrowserSessionUpdate {
	_u.mutation.SetUserDataDir(v)
	return _u
}

// SetNillableUserDataDir sets the "user_data_dir" field if the given value is not nil.
func (_u *BrowserSessionUpdate) SetNillableUserDataDir(v *string) *BrowserSessionUpdate {
	if v != nil {
		_u.SetUserDataDir(*v)
	}
	return _u
}

// SetHeadless sets the "headless" field.
func (_u *BrowserSessionUpdate) SetHeadless(v bool) *BrowserSessionUpdate {
	_u.mutation.SetHeadless(v)
	return _u
}

// SetNillableHeadless sets the "headless" field if the given value is not nil.
func (_u *BrowserSessionUpdate) SetNillableHeadless(v *bool) *BrowserSessionUpdate {
	if v != nil {
		_u.SetHeadless(*v)
	}
	return _u
}

// SetProxy sets the "proxy" field.
func (_u *BrowserSessionUpdate) SetProxy(v string) *BrowserSessionUpdate {
	_u.mutation.SetProxy(v)
	return _u
}

// SetNillableProxy sets the "proxy" field if the given value is not nil.
func (_u *BrowserSessionUpdate) SetNillableProxy(v *string) *BrowserSessionUpdate {
	if v != nil {
		_u.SetProxy(*v)
	}
	return _u
}

// ClearProxy clears the value of the "proxy" field.
func (_u *BrowserSessionUpdate) ClearProxy() *BrowserSessionUpdate {
	_u.mutation.ClearProxy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BrowserSessionUpdate) SetUpdatedAt(v time.Time) *BrowserSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSheepID sets the "sheep" edge to the Sheep entity by ID.
func (_u *BrowserSessionUpdate) SetSheepID(id int) *BrowserSessionUpdate {
	_u.mutation.SetSheepID(id)
	return _u
}

// SetSheep sets the "sheep" edge to the Sheep entity.
func (_u *BrowserSessionUpdate) SetSheep(v *Sheep) *BrowserSessionUpdate {
	return _u.SetSheepID(v.ID)
}

// Mutation returns the BrowserSessionMutation object of the builder.
func (_u *BrowserSessionUpdate) Mutation() *BrowserSessionMutation {
	return _u.mutation
}

// ClearSheep clears the "sheep" edge to the Sheep entity.
func (_u *BrowserSessionUpdate) ClearSheep() *BrowserSessionUpdate {
	_u.mutation.ClearSheep()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BrowserSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BrowserSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BrowserSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BrowserSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BrowserSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := browsersession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BrowserSessionUpdate) check() error {
	if v, ok := _u.mutation.UserDataDir(); ok {
		if err := browsersession.UserDataDirValidator(v); err != nil {
			return &ValidationError{Name: "user_data_dir", err: fmt.Errorf(`ent: validator failed for field "BrowserSession.user_data_dir": %w`, err)}
		}
	}
	if _u.mutation.SheepCleared() && len(_u.mutation.SheepIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BrowserSession.sheep"`)
	}
	return nil
}

func (_u *BrowserSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(browsersession.Table, browsersession.Columns, sqlgraph.NewFieldSpec(browsersession.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserDataDir(); ok {
		_spec.SetField(browsersession.FieldUserDataDir, field.TypeString, value)
	}
	if value, ok := _u.mutation.Headless(); ok {
		_spec.SetField(browsersession.FieldHeadless, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Proxy(); ok {
		_spec.SetField(browsersession.FieldProxy, field.TypeString, value)
	}
	if _u.mutation.ProxyCleared() {
		_spec.ClearField(browsersession.FieldProxy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(browsersession.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SheepCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   browsersession.SheepTable,
			Columns: []string{browsersession.SheepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sheep.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SheepIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   browsersession.SheepTable,
			Columns: []string{browsersession.SheepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sheep.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{browsersession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BrowserSessionUpdateOne is the builder for updating a single BrowserSession entity.
type BrowserSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BrowserSessionMutation
}

// SetUserDataDir sets the "user_data_dir" field.
func (_u *BrowserSessionUpdateOne) SetUserDataDir(v string) *BrowserSessionUpdateOne {
	_u.mutation.SetUserDataDir(v)
	return _u
}

// SetNillableUserDataDir sets the "user_data_dir" field if the given value is not nil.
func (_u *BrowserSessionUpdateOne) SetNillableUserDataDir(v *string) *BrowserSessionUpdateOne {
	if v != nil {
		_u.SetUserDataDir(*v)
	}
	return _u
}

// SetHeadless sets the "headless" field.
func (_u *BrowserSessionUpdateOne) SetHeadless(v bool) *BrowserSessionUpdateOne {
	_u.mutation.SetHeadless(v)
	return _u
}

// SetNillableHeadless sets the "headless" field if the given value is not nil.
func (_u *BrowserSessionUpdateOne) SetNillableHeadless(v *bool) *BrowserSessionUpdateOne {
	if v != nil {
		_u.SetHeadless(*v)
	}
	return _u
}

// SetProxy sets the "proxy" field.
func (_u *BrowserSessionUpdateOne) SetProxy(v string) *BrowserSessionUpdateOne {
	_u.mutation.SetProxy(v)
	return _u
}

// SetNillableProxy sets the "proxy" field if the given value is not nil.
func (_u *BrowserSessionUpdateOne) SetNillableProxy(v *string) *BrowserSessionUpdateOne {
	if v != nil {
		_u.SetProxy(*v)
	}
	return _u
}

// ClearProxy clears the value of the "proxy" field.
func (_u *BrowserSessionUpdateOne) ClearProxy() *BrowserSessionUpdateOne {
	_u.mutation.ClearProxy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BrowserSessionUpdateOne) SetUpdatedAt(v time.Time) *BrowserSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSheepID sets the "sheep" edge to the Sheep entity by ID.
func (_u *BrowserSessionUpdateOne) SetSheepID(id int) *BrowserSessionUpdateOne {
	_u.mutation.SetSheepID(id)
	return _u
}

// SetSheep sets the "sheep" edge to the Sheep entity.
func (_u *BrowserSessionUpdateOne) SetSheep(v *Sheep) *BrowserSessionUpdateOne {
	return _u.SetSheepID(v.ID)
}

// Mutation returns the BrowserSessionMutation object of the builder.
func (_u *BrowserSessionUpdateOne) Mutation() *BrowserSessionMutation {
	return _u.mutation
}

// ClearSheep clears the "sheep" edge to the Sheep entity.
func (_u *BrowserSessionUpdateOne) ClearSheep() *BrowserSessionUpdateOne {
	_u.mutation.ClearSheep()
	return _u
}

// Where appends a list predicates to the BrowserSessionUpdate builder.
func (_u *BrowserSessionUpdateOne) Where(ps ...predicate.BrowserSession) *BrowserSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BrowserSessionUpdateOne) Select(field string, fields ...string) *BrowserSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BrowserSession entity.
func (_u *BrowserSessionUpdateOne) Save(ctx context.Context) (*BrowserSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BrowserSessionUpdateOne) SaveX(ctx context.Context) *BrowserSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BrowserSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BrowserSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BrowserSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := browsersession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BrowserSessionUpdateOne) check() error {
	if v, ok := _u.mutation.UserDataDir(); ok {
		if err := browsersession.UserDataDirValidator(v); err != nil {
			return &ValidationError{Name: "user_data_dir", err: fmt.Errorf(`ent: validator failed for field "BrowserSession.user_data_dir": %w`, err)}
		}
	}
	if _u.mutation.SheepCleared() && len(_u.mutation.SheepIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BrowserSession.sheep"`)
	}
	return nil
}

func (_u *BrowserSessionUpdateOne) sqlSave(ctx context.Context) (_node *BrowserSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(browsersession.Table, browsersession.Columns, sqlgraph.NewFieldSpec(browsersession.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BrowserSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, browsersession.FieldID)
		for _, f := range fields {
			if !browsersession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != browsersession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserDataDir(); ok {
		_spec.SetField(browsersession.FieldUserDataDir, field.TypeString, value)
	}
	if value, ok := _u.mutation.Headless(); ok {
		_spec.SetField(browsersession.FieldHeadless, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Proxy(); ok {
		_spec.SetField(browsersession.FieldProxy, field.TypeString, value)
	}
	if _u.mutation.ProxyCleared() {
		_spec.ClearField(browsersession.FieldProxy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(browsersession.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SheepCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   browsersession.SheepTable,
			Columns: []string{browsersession.SheepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sheep.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SheepIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   browsersession.SheepTable,
			Columns: []string{browsersession.SheepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sheep.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BrowserSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{browsersession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
