// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agurrrrr/shepherd/ent/mcpserver"
)

// MCPServerCreate is the builder for creating a MCPServer entity.
type MCPServerCreate struct {
	config
	mutation *MCPServerMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *MCPServerCreate) SetName(v string) *MCPServerCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *MCPServerCreate) SetLabel(v string) *MCPServerCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *MCPServerCreate) SetNillableLabel(v *string) *MCPServerCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *MCPServerCreate) SetDescription(v string) *MCPServerCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MCPServerCreate) SetNillableDescription(v *string) *MCPServerCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetTransport sets the "transport" field.
func (_c *MCPServerCreate) SetTransport(v mcpserver.Transport) *MCPServerCreate {
	_c.mutation.SetTransport(v)
	return _c
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_c *MCPServerCreate) SetNillableTransport(v *mcpserver.Transport) *MCPServerCreate {
	if v != nil {
		_c.SetTransport(*v)
	}
	return _c
}

// SetCommand sets the "command" field.
func (_c *MCPServerCreate) SetCommand(v string) *MCPServerCreate {
	_c.mutation.SetCommand(v)
	return _c
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_c *MCPServerCreate) SetNillableCommand(v *string) *MCPServerCreate {
	if v != nil {
		_c.SetCommand(*v)
	}
	return _c
}

// SetArgs sets the "args" field.
func (_c *MCPServerCreate) SetArgs(v string) *MCPServerCreate {
	_c.mutation.SetArgs(v)
	return _c
}

// SetNillableArgs sets the "args" field if the given value is not nil.
func (_c *MCPServerCreate) SetNillableArgs(v *string) *MCPServerCreate {
	if v != nil {
		_c.SetArgs(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *MCPServerCreate) SetURL(v string) *MCPServerCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *MCPServerCreate) SetNillableURL(v *string) *MCPServerCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetEnv sets the "env" field.
func (_c *MCPServerCreate) SetEnv(v string) *MCPServerCreate {
	_c.mutation.SetEnv(v)
	return _c
}

// SetNillableEnv sets the "env" field if the given value is not nil.
func (_c *MCPServerCreate) SetNillableEnv(v *string) *MCPServerCreate {
	if v != nil {
		_c.SetEnv(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *MCPServerCreate) SetEnabled(v bool) *MCPServerCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *MCPServerCreate) SetNillableEnabled(v *bool) *MCPServerCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MCPServerCreate) SetCreatedAt(v time.Time) *MCPServerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MCPServerCreate) SetNillableCreatedAt(v *time.Time) *MCPServerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MCPServerCreate) SetUpdatedAt(v time.Time) *MCPServerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MCPServerCreate) SetNillableUpdatedAt(v *time.Time) *MCPServerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the MCPServerMutation object of the builder.
func (_c *MCPServerCreate) Mutation() *MCPServerMutation {
	return _c.mutation
}

// Save creates the MCPServer in the database.
func (_c *MCPServerCreate) Save(ctx context.Context) (*MCPServer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MCPServerCreate) SaveX(ctx context.Context) *MCPServer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MCPServerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MCPServerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MCPServerCreate) defaults() {
	if _, ok := _c.mutation.Transport(); !ok {
		v := mcpserver.DefaultTransport
		_c.mutation.SetTransport(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := mcpserver.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mcpserver.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mcpserver.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MCPServerCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MCPServer.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := mcpserver.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MCPServer.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Transport(); !ok {
		return &ValidationError{Name: "transport", err: errors.New(`ent: missing required field "MCPServer.transport"`)}
	}
	if v, ok := _c.mutation.Transport(); ok {
		if err := mcpserver.TransportValidator(v); err != nil {
			return &ValidationError{Name: "transport", err: fmt.Errorf(`ent: validator failed for field "MCPServer.transport": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "MCPServer.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MCPServer.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MCPServer.updated_at"`)}
	}
	return nil
}

func (_c *MCPServerCreate) sqlSave(ctx context.Context) (*MCPServer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MCPServerCreate) createSpec() (*MCPServer, *sqlgraph.CreateSpec) {
	var (
		_node = &MCPServer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mcpserver.Table, sqlgraph.NewFieldSpec(mcpserver.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(mcpserver.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(mcpserver.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(mcpserver.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Transport(); ok {
		_spec.SetField(mcpserver.FieldTransport, field.TypeEnum, value)
		_node.Transport = value
	}
	if value, ok := _c.mutation.Command(); ok {
		_spec.SetField(mcpserver.FieldCommand, field.TypeString, value)
		_node.Command = value
	}
	if value, ok := _c.mutation.Args(); ok {
		_spec.SetField(mcpserver.FieldArgs, field.TypeString, value)
		_node.Args = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(mcpserver.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Env(); ok {
		_spec.SetField(mcpserver.FieldEnv, field.TypeString, value)
		_node.Env = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(mcpserver.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mcpserver.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mcpserver.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// MCPServerCreateBulk is the builder for creating many MCPServer entities in bulk.
type MCPServerCreateBulk struct {
	config
	err      error
	builders []*MCPServerCreate
}

// Save creates the MCPServer entities in the database.
func (_c *MCPServerCreateBulk) Save(ctx context.Context) ([]*MCPServer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MCPServer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MCPServerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MCPServerCreateBulk) SaveX(ctx context.Context) []*MCPServer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MCPServerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MCPServerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
