// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agurrrrr/shepherd/ent/mcpserver"
	"github.com/agurrrrr/shepherd/ent/predicate"
)

// MCPServerUpdate is the builder for updating MCPServer entities.
type MCPServerUpdate struct {
	config
	hooks    []Hook
	mutation *MCPServerMutation
}

// Where appends a list predicates to the MCPServerUpdate builder.
func (_u *MCPServerUpdate) Where(ps ...predicate.MCPServer) *MCPServerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *MCPServerUpdate) SetName(v string) *MCPServerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableName(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *MCPServerUpdate) SetLabel(v string) *MCPServerUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableLabel(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *MCPServerUpdate) ClearLabel() *MCPServerUpdate {
	_u.mutation.ClearLabel()
	return _u
}

// SetDescription sets the "description" field.
func (_u *MCPServerUpdate) SetDescription(v string) *MCPServerUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableDescription(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *MCPServerUpdate) ClearDescription() *MCPServerUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetTransport sets the "transport" field.
func (_u *MCPServerUpdate) SetTransport(v mcpserver.Transport) *MCPServerUpdate {
	_u.mutation.SetTransport(v)
	return _u
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableTransport(v *mcpserver.Transport) *MCPServerUpdate {
	if v != nil {
		_u.SetTransport(*v)
	}
	return _u
}

// SetCommand sets the "command" field.
func (_u *MCPServerUpdate) SetCommand(v string) *MCPServerUpdate {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableCommand(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *MCPServerUpdate) ClearCommand() *MCPServerUpdate {
	_u.mutation.ClearCommand()
	return _u
}

// SetArgs sets the "args" field.
func (_u *MCPServerUpdate) SetArgs(v string) *MCPServerUpdate {
	_u.mutation.SetArgs(v)
	return _u
}

// SetNillableArgs sets the "args" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableArgs(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetArgs(*v)
	}
	return _u
}

// ClearArgs clears the value of the "args" field.
func (_u *MCPServerUpdate) ClearArgs() *MCPServerUpdate {
	_u.mutation.ClearArgs()
	return _u
}

// SetURL sets the "url" field.
func (_u *MCPServerUpdate) SetURL(v string) *MCPServerUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableURL(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *MCPServerUpdate) ClearURL() *MCPServerUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetEnv sets the "env" field.
func (_u *MCPServerUpdate) SetEnv(v string) *MCPServerUpdate {
	_u.mutation.SetEnv(v)
	return _u
}

// SetNillableEnv sets the "env" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableEnv(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetEnv(*v)
	}
	return _u
}

// ClearEnv clears the value of the "env" field.
func (_u *MCPServerUpdate) ClearEnv() *MCPServerUpdate {
	_u.mutation.ClearEnv()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *MCPServerUpdate) SetEnabled(v bool) *MCPServerUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableEnabled(v *bool) *MCPServerUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MCPServerUpdate) SetUpdatedAt(v time.Time) *MCPServerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MCPServerMutation object of the builder.
func (_u *MCPServerUpdate) Mutation() *MCPServerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MCPServerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MCPServerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MCPServerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MCPServerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MCPServerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mcpserver.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MCPServerUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := mcpserver.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MCPServer.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Transport(); ok {
		if err := mcpserver.TransportValidator(v); err != nil {
			return &ValidationError{Name: "transport", err: fmt.Errorf(`ent: validator failed for field "MCPServer.transport": %w`, err)}
		}
	}
	return nil
}

func (_u *MCPServerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mcpserver.Table, mcpserver.Columns, sqlgraph.NewFieldSpec(mcpserver.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mcpserver.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(mcpserver.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(mcpserver.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(mcpserver.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(mcpserver.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Transport(); ok {
		_spec.SetField(mcpserver.FieldTransport, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(mcpserver.FieldCommand, field.TypeString, value)
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(mcpserver.FieldCommand, field.TypeString)
	}
	if value, ok := _u.mutation.Args(); ok {
		_spec.SetField(mcpserver.FieldArgs, field.TypeString, value)
	}
	if _u.mutation.ArgsCleared() {
		_spec.ClearField(mcpserver.FieldArgs, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(mcpserver.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(mcpserver.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Env(); ok {
		_spec.SetField(mcpserver.FieldEnv, field.TypeString, value)
	}
	if _u.mutation.EnvCleared() {
		_spec.ClearField(mcpserver.FieldEnv, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(mcpserver.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mcpserver.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcpserver.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MCPServerUpdateOne is the builder for updating a single MCPServer entity.
type MCPServerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MCPServerMutation
}

// SetName sets the "name" field.
func (_u *MCPServerUpdateOne) SetName(v string) *MCPServerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableName(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *MCPServerUpdateOne) SetLabel(v string) *MCPServerUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableLabel(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *MCPServerUpdateOne) ClearLabel() *MCPServerUpdateOne {
	_u.mutation.ClearLabel()
	return _u
}

// SetDescription sets the "description" field.
func (_u *MCPServerUpdateOne) SetDescription(v string) *MCPServerUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableDescription(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *MCPServerUpdateOne) ClearDescription() *MCPServerUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetTransport sets the "transport" field.
func (_u *MCPServerUpdateOne) SetTransport(v mcpserver.Transport) *MCPServerUpdateOne {
	_u.mutation.SetTransport(v)
	return _u
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableTransport(v *mcpserver.Transport) *MCPServerUpdateOne {
	if v != nil {
		_u.SetTransport(*v)
	}
	return _u
}

// SetCommand sets the "command" field.
func (_u *MCPServerUpdateOne) SetCommand(v string) *MCPServerUpdateOne {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableCommand(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *MCPServerUpdateOne) ClearCommand() *MCPServerUpdateOne {
	_u.mutation.ClearCommand()
	return _u
}

// SetArgs sets the "args" field.
func (_u *MCPServerUpdateOne) SetArgs(v string) *MCPServerUpdateOne {
	_u.mutation.SetArgs(v)
	return _u
}

// SetNillableArgs sets the "args" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableArgs(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetArgs(*v)
	}
	return _u
}

// ClearArgs clears the value of the "args" field.
func (_u *MCPServerUpdateOne) ClearArgs() *MCPServerUpdateOne {
	_u.mutation.ClearArgs()
	return _u
}

// SetURL sets the "url" field.
func (_u *MCPServerUpdateOne) SetURL(v string) *MCPServerUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableURL(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *MCPServerUpdateOne) ClearURL() *MCPServerUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetEnv sets the "env" field.
func (_u *MCPServerUpdateOne) SetEnv(v string) *MCPServerUpdateOne {
	_u.mutation.SetEnv(v)
	return _u
}

// SetNillableEnv sets the "env" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableEnv(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetEnv(*v)
	}
	return _u
}

// ClearEnv clears the value of the "env" field.
func (_u *MCPServerUpdateOne) ClearEnv() *MCPServerUpdateOne {
	_u.mutation.ClearEnv()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *MCPServerUpdateOne) SetEnabled(v bool) *MCPServerUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableEnabled(v *bool) *MCPServerUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MCPServerUpdateOne) SetUpdatedAt(v time.Time) *MCPServerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MCPServerMutation object of the builder.
func (_u *MCPServerUpdateOne) Mutation() *MCPServerMutation {
	return _u.mutation
}

// Where appends a list predicates to the MCPServerUpdate builder.
func (_u *MCPServerUpdateOne) Where(ps ...predicate.MCPServer) *MCPServerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MCPServerUpdateOne) Select(field string, fields ...string) *MCPServerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MCPServer entity.
func (_u *MCPServerUpdateOne) Save(ctx context.Context) (*MCPServer, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MCPServerUpdateOne) SaveX(ctx context.Context) *MCPServer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MCPServerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MCPServerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MCPServerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mcpserver.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MCPServerUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := mcpserver.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MCPServer.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Transport(); ok {
		if err := mcpserver.TransportValidator(v); err != nil {
			return &ValidationError{Name: "transport", err: fmt.Errorf(`ent: validator failed for field "MCPServer.transport": %w`, err)}
		}
	}
	return nil
}

func (_u *MCPServerUpdateOne) sqlSave(ctx context.Context) (_node *MCPServer, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mcpserver.Table, mcpserver.Columns, sqlgraph.NewFieldSpec(mcpserver.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MCPServer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mcpserver.FieldID)
		for _, f := range fields {
			if !mcpserver.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mcpserver.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mcpserver.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(mcpserver.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(mcpserver.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(mcpserver.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(mcpserver.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Transport(); ok {
		_spec.SetField(mcpserver.FieldTransport, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(mcpserver.FieldCommand, field.TypeString, value)
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(mcpserver.FieldCommand, field.TypeString)
	}
	if value, ok := _u.mutation.Args(); ok {
		_spec.SetField(mcpserver.FieldArgs, field.TypeString, value)
	}
	if _u.mutation.ArgsCleared() {
		_spec.ClearField(mcpserver.FieldArgs, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(mcpserver.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(mcpserver.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Env(); ok {
		_spec.SetField(mcpserver.FieldEnv, field.TypeString, value)
	}
	if _u.mutation.EnvCleared() {
		_spec.ClearField(mcpserver.FieldEnv, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(mcpserver.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mcpserver.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &MCPServer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcpserver.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
