// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/agurrrrr/shepherd/ent/project"
	"github.com/agurrrrr/shepherd/ent/sheep"
)

// Project is the model entity for the Project schema.
type Project struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 프로젝트 이름
	Name string `json:"name,omitempty"`
	// 프로젝트 경로
	Path string `json:"path,omitempty"`
	// 프로젝트 설명
	Description string `json:"description,omitempty"`
	// git origin에서 추출한 저장소 HTTPS URL (거의 변하지 않으므로 캐시)
	RepoURL string `json:"repo_url,omitempty"`
	// 프로젝트별 MCP 서버 활성화 설정: {server_name: {enabled: bool}}
	McpServers map[string]interface{} `json:"mcp_servers,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectQuery when eager-loading is set.
	Edges        ProjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectEdges holds the relations/edges for other nodes in the graph.
type ProjectEdges struct {
	// Sheep holds the value of the sheep edge.
	Sheep *Sheep `json:"sheep,omitempty"`
	// Tasks holds the value of the tasks edge.
	Tasks []*Task `json:"tasks,omitempty"`
	// Schedules holds the value of the schedules edge.
	Schedules []*Schedule `json:"schedules,omitempty"`
	// Skills holds the value of the skills edge.
	Skills []*Skill `json:"skills,omitempty"`
	// WikiPages holds the value of the wiki_pages edge.
	WikiPages []*WikiPage `json:"wiki_pages,omitempty"`
	// WikiVersions holds the value of the wiki_versions edge.
	WikiVersions []*WikiPageVersion `json:"wiki_versions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// SheepOrErr returns the Sheep value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectEdges) SheepOrErr() (*Sheep, error) {
	if e.Sheep != nil {
		return e.Sheep, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: sheep.Label}
	}
	return nil, &NotLoadedError{edge: "sheep"}
}

// TasksOrErr returns the Tasks value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) TasksOrErr() ([]*Task, error) {
	if e.loadedTypes[1] {
		return e.Tasks, nil
	}
	return nil, &NotLoadedError{edge: "tasks"}
}

// SchedulesOrErr returns the Schedules value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) SchedulesOrErr() ([]*Schedule, error) {
	if e.loadedTypes[2] {
		return e.Schedules, nil
	}
	return nil, &NotLoadedError{edge: "schedules"}
}

// SkillsOrErr returns the Skills value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) SkillsOrErr() ([]*Skill, error) {
	if e.loadedTypes[3] {
		return e.Skills, nil
	}
	return nil, &NotLoadedError{edge: "skills"}
}

// WikiPagesOrErr returns the WikiPages value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) WikiPagesOrErr() ([]*WikiPage, error) {
	if e.loadedTypes[4] {
		return e.WikiPages, nil
	}
	return nil, &NotLoadedError{edge: "wiki_pages"}
}

// WikiVersionsOrErr returns the WikiVersions value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) WikiVersionsOrErr() ([]*WikiPageVersion, error) {
	if e.loadedTypes[5] {
		return e.WikiVersions, nil
	}
	return nil, &NotLoadedError{edge: "wiki_versions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Project) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case project.FieldMcpServers:
			values[i] = new([]byte)
		case project.FieldID:
			values[i] = new(sql.NullInt64)
		case project.FieldName, project.FieldPath, project.FieldDescription, project.FieldRepoURL:
			values[i] = new(sql.NullString)
		case project.FieldCreatedAt, project.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Project fields.
func (_m *Project) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case project.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case project.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case project.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case project.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case project.FieldRepoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_url", values[i])
			} else if value.Valid {
				_m.RepoURL = value.String
			}
		case project.FieldMcpServers:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field mcp_servers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.McpServers); err != nil {
					return fmt.Errorf("unmarshal field mcp_servers: %w", err)
				}
			}
		case project.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case project.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Project.
// This includes values selected through modifiers, order, etc.
func (_m *Project) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySheep queries the "sheep" edge of the Project entity.
func (_m *Project) QuerySheep() *SheepQuery {
	return NewProjectClient(_m.config).QuerySheep(_m)
}

// QueryTasks queries the "tasks" edge of the Project entity.
func (_m *Project) QueryTasks() *TaskQuery {
	return NewProjectClient(_m.config).QueryTasks(_m)
}

// QuerySchedules queries the "schedules" edge of the Project entity.
func (_m *Project) QuerySchedules() *ScheduleQuery {
	return NewProjectClient(_m.config).QuerySchedules(_m)
}

// QuerySkills queries the "skills" edge of the Project entity.
func (_m *Project) QuerySkills() *SkillQuery {
	return NewProjectClient(_m.config).QuerySkills(_m)
}

// QueryWikiPages queries the "wiki_pages" edge of the Project entity.
func (_m *Project) QueryWikiPages() *WikiPageQuery {
	return NewProjectClient(_m.config).QueryWikiPages(_m)
}

// QueryWikiVersions queries the "wiki_versions" edge of the Project entity.
func (_m *Project) QueryWikiVersions() *WikiPageVersionQuery {
	return NewProjectClient(_m.config).QueryWikiVersions(_m)
}

// Update returns a builder for updating this Project.
// Note that you need to call Project.Unwrap() before calling this method if this Project
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Project) Update() *ProjectUpdateOne {
	return NewProjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Project entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Project) Unwrap() *Project {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Project is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Project) String() string {
	var builder strings.Builder
	builder.WriteString("Project(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("repo_url=")
	builder.WriteString(_m.RepoURL)
	builder.WriteString(", ")
	builder.WriteString("mcp_servers=")
	builder.WriteString(fmt.Sprintf("%v", _m.McpServers))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Projects is a parsable slice of Project.
type Projects []*Project
