// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/agurrrrr/shepherd/ent/browsersession"
	"github.com/agurrrrr/shepherd/ent/issue"
	"github.com/agurrrrr/shepherd/ent/mcpserver"
	"github.com/agurrrrr/shepherd/ent/project"
	"github.com/agurrrrr/shepherd/ent/schedule"
	"github.com/agurrrrr/shepherd/ent/schema"
	"github.com/agurrrrr/shepherd/ent/sheep"
	"github.com/agurrrrr/shepherd/ent/sheepname"
	"github.com/agurrrrr/shepherd/ent/skill"
	"github.com/agurrrrr/shepherd/ent/task"
	"github.com/agurrrrr/shepherd/ent/wikipage"
	"github.com/agurrrrr/shepherd/ent/wikipageversion"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	browsersessionFields := schema.BrowserSession{}.Fields()
	_ = browsersessionFields
	// browsersessionDescUserDataDir is the schema descriptor for user_data_dir field.
	browsersessionDescUserDataDir := browsersessionFields[0].Descriptor()
	// browsersession.UserDataDirValidator is a validator for the "user_data_dir" field. It is called by the builders before save.
	browsersession.UserDataDirValidator = browsersessionDescUserDataDir.Validators[0].(func(string) error)
	// browsersessionDescHeadless is the schema descriptor for headless field.
	browsersessionDescHeadless := browsersessionFields[1].Descriptor()
	// browsersession.DefaultHeadless holds the default value on creation for the headless field.
	browsersession.DefaultHeadless = browsersessionDescHeadless.Default.(bool)
	// browsersessionDescCreatedAt is the schema descriptor for created_at field.
	browsersessionDescCreatedAt := browsersessionFields[3].Descriptor()
	// browsersession.DefaultCreatedAt holds the default value on creation for the created_at field.
	browsersession.DefaultCreatedAt = browsersessionDescCreatedAt.Default.(func() time.Time)
	// browsersessionDescUpdatedAt is the schema descriptor for updated_at field.
	browsersessionDescUpdatedAt := browsersessionFields[4].Descriptor()
	// browsersession.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	browsersession.DefaultUpdatedAt = browsersessionDescUpdatedAt.Default.(func() time.Time)
	// browsersession.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	browsersession.UpdateDefaultUpdatedAt = browsersessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	issueFields := schema.Issue{}.Fields()
	_ = issueFields
	// issueDescTitle is the schema descriptor for title field.
	issueDescTitle := issueFields[0].Descriptor()
	// issue.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	issue.TitleValidator = issueDescTitle.Validators[0].(func(string) error)
	// issueDescCreatedAt is the schema descriptor for created_at field.
	issueDescCreatedAt := issueFields[5].Descriptor()
	// issue.DefaultCreatedAt holds the default value on creation for the created_at field.
	issue.DefaultCreatedAt = issueDescCreatedAt.Default.(func() time.Time)
	// issueDescUpdatedAt is the schema descriptor for updated_at field.
	issueDescUpdatedAt := issueFields[6].Descriptor()
	// issue.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	issue.DefaultUpdatedAt = issueDescUpdatedAt.Default.(func() time.Time)
	// issue.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	issue.UpdateDefaultUpdatedAt = issueDescUpdatedAt.UpdateDefault.(func() time.Time)
	mcpserverFields := schema.MCPServer{}.Fields()
	_ = mcpserverFields
	// mcpserverDescName is the schema descriptor for name field.
	mcpserverDescName := mcpserverFields[0].Descriptor()
	// mcpserver.NameValidator is a validator for the "name" field. It is called by the builders before save.
	mcpserver.NameValidator = mcpserverDescName.Validators[0].(func(string) error)
	// mcpserverDescEnabled is the schema descriptor for enabled field.
	mcpserverDescEnabled := mcpserverFields[8].Descriptor()
	// mcpserver.DefaultEnabled holds the default value on creation for the enabled field.
	mcpserver.DefaultEnabled = mcpserverDescEnabled.Default.(bool)
	// mcpserverDescCreatedAt is the schema descriptor for created_at field.
	mcpserverDescCreatedAt := mcpserverFields[9].Descriptor()
	// mcpserver.DefaultCreatedAt holds the default value on creation for the created_at field.
	mcpserver.DefaultCreatedAt = mcpserverDescCreatedAt.Default.(func() time.Time)
	// mcpserverDescUpdatedAt is the schema descriptor for updated_at field.
	mcpserverDescUpdatedAt := mcpserverFields[10].Descriptor()
	// mcpserver.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mcpserver.DefaultUpdatedAt = mcpserverDescUpdatedAt.Default.(func() time.Time)
	// mcpserver.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mcpserver.UpdateDefaultUpdatedAt = mcpserverDescUpdatedAt.UpdateDefault.(func() time.Time)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[0].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = projectDescName.Validators[0].(func(string) error)
	// projectDescPath is the schema descriptor for path field.
	projectDescPath := projectFields[1].Descriptor()
	// project.PathValidator is a validator for the "path" field. It is called by the builders before save.
	project.PathValidator = projectDescPath.Validators[0].(func(string) error)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[5].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[6].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	scheduleFields := schema.Schedule{}.Fields()
	_ = scheduleFields
	// scheduleDescName is the schema descriptor for name field.
	scheduleDescName := scheduleFields[0].Descriptor()
	// schedule.NameValidator is a validator for the "name" field. It is called by the builders before save.
	schedule.NameValidator = scheduleDescName.Validators[0].(func(string) error)
	// scheduleDescPrompt is the schema descriptor for prompt field.
	scheduleDescPrompt := scheduleFields[1].Descriptor()
	// schedule.PromptValidator is a validator for the "prompt" field. It is called by the builders before save.
	schedule.PromptValidator = scheduleDescPrompt.Validators[0].(func(string) error)
	// scheduleDescEnabled is the schema descriptor for enabled field.
	scheduleDescEnabled := scheduleFields[5].Descriptor()
	// schedule.DefaultEnabled holds the default value on creation for the enabled field.
	schedule.DefaultEnabled = scheduleDescEnabled.Default.(bool)
	// scheduleDescCreatedAt is the schema descriptor for created_at field.
	scheduleDescCreatedAt := scheduleFields[8].Descriptor()
	// schedule.DefaultCreatedAt holds the default value on creation for the created_at field.
	schedule.DefaultCreatedAt = scheduleDescCreatedAt.Default.(func() time.Time)
	// scheduleDescUpdatedAt is the schema descriptor for updated_at field.
	scheduleDescUpdatedAt := scheduleFields[9].Descriptor()
	// schedule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	schedule.DefaultUpdatedAt = scheduleDescUpdatedAt.Default.(func() time.Time)
	// schedule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	schedule.UpdateDefaultUpdatedAt = scheduleDescUpdatedAt.UpdateDefault.(func() time.Time)
	sheepFields := schema.Sheep{}.Fields()
	_ = sheepFields
	// sheepDescName is the schema descriptor for name field.
	sheepDescName := sheepFields[0].Descriptor()
	// sheep.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sheep.NameValidator = sheepDescName.Validators[0].(func(string) error)
	// sheepDescConsecutiveFailures is the schema descriptor for consecutive_failures field.
	sheepDescConsecutiveFailures := sheepFields[4].Descriptor()
	// sheep.DefaultConsecutiveFailures holds the default value on creation for the consecutive_failures field.
	sheep.DefaultConsecutiveFailures = sheepDescConsecutiveFailures.Default.(int)
	// sheepDescCreatedAt is the schema descriptor for created_at field.
	sheepDescCreatedAt := sheepFields[5].Descriptor()
	// sheep.DefaultCreatedAt holds the default value on creation for the created_at field.
	sheep.DefaultCreatedAt = sheepDescCreatedAt.Default.(func() time.Time)
	// sheepDescUpdatedAt is the schema descriptor for updated_at field.
	sheepDescUpdatedAt := sheepFields[6].Descriptor()
	// sheep.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sheep.DefaultUpdatedAt = sheepDescUpdatedAt.Default.(func() time.Time)
	// sheep.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sheep.UpdateDefaultUpdatedAt = sheepDescUpdatedAt.UpdateDefault.(func() time.Time)
	sheepnameFields := schema.SheepName{}.Fields()
	_ = sheepnameFields
	// sheepnameDescName is the schema descriptor for name field.
	sheepnameDescName := sheepnameFields[0].Descriptor()
	// sheepname.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sheepname.NameValidator = sheepnameDescName.Validators[0].(func(string) error)
	// sheepnameDescPriority is the schema descriptor for priority field.
	sheepnameDescPriority := sheepnameFields[1].Descriptor()
	// sheepname.DefaultPriority holds the default value on creation for the priority field.
	sheepname.DefaultPriority = sheepnameDescPriority.Default.(int)
	// sheepnameDescCreatedAt is the schema descriptor for created_at field.
	sheepnameDescCreatedAt := sheepnameFields[2].Descriptor()
	// sheepname.DefaultCreatedAt holds the default value on creation for the created_at field.
	sheepname.DefaultCreatedAt = sheepnameDescCreatedAt.Default.(func() time.Time)
	skillFields := schema.Skill{}.Fields()
	_ = skillFields
	// skillDescName is the schema descriptor for name field.
	skillDescName := skillFields[0].Descriptor()
	// skill.NameValidator is a validator for the "name" field. It is called by the builders before save.
	skill.NameValidator = skillDescName.Validators[0].(func(string) error)
	// skillDescContent is the schema descriptor for content field.
	skillDescContent := skillFields[2].Descriptor()
	// skill.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	skill.ContentValidator = skillDescContent.Validators[0].(func(string) error)
	// skillDescEnabled is the schema descriptor for enabled field.
	skillDescEnabled := skillFields[4].Descriptor()
	// skill.DefaultEnabled holds the default value on creation for the enabled field.
	skill.DefaultEnabled = skillDescEnabled.Default.(bool)
	// skillDescBundled is the schema descriptor for bundled field.
	skillDescBundled := skillFields[6].Descriptor()
	// skill.DefaultBundled holds the default value on creation for the bundled field.
	skill.DefaultBundled = skillDescBundled.Default.(bool)
	// skillDescEffort is the schema descriptor for effort field.
	skillDescEffort := skillFields[7].Descriptor()
	// skill.DefaultEffort holds the default value on creation for the effort field.
	skill.DefaultEffort = skillDescEffort.Default.(string)
	// skillDescMaxTurns is the schema descriptor for max_turns field.
	skillDescMaxTurns := skillFields[8].Descriptor()
	// skill.DefaultMaxTurns holds the default value on creation for the max_turns field.
	skill.DefaultMaxTurns = skillDescMaxTurns.Default.(int)
	// skillDescCreatedAt is the schema descriptor for created_at field.
	skillDescCreatedAt := skillFields[10].Descriptor()
	// skill.DefaultCreatedAt holds the default value on creation for the created_at field.
	skill.DefaultCreatedAt = skillDescCreatedAt.Default.(func() time.Time)
	// skillDescUpdatedAt is the schema descriptor for updated_at field.
	skillDescUpdatedAt := skillFields[11].Descriptor()
	// skill.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	skill.DefaultUpdatedAt = skillDescUpdatedAt.Default.(func() time.Time)
	// skill.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	skill.UpdateDefaultUpdatedAt = skillDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescPrompt is the schema descriptor for prompt field.
	taskDescPrompt := taskFields[0].Descriptor()
	// task.PromptValidator is a validator for the "prompt" field. It is called by the builders before save.
	task.PromptValidator = taskDescPrompt.Validators[0].(func(string) error)
	// taskDescCostUsd is the schema descriptor for cost_usd field.
	taskDescCostUsd := taskFields[7].Descriptor()
	// task.DefaultCostUsd holds the default value on creation for the cost_usd field.
	task.DefaultCostUsd = taskDescCostUsd.Default.(float64)
	// taskDescPromptTokens is the schema descriptor for prompt_tokens field.
	taskDescPromptTokens := taskFields[8].Descriptor()
	// task.DefaultPromptTokens holds the default value on creation for the prompt_tokens field.
	task.DefaultPromptTokens = taskDescPromptTokens.Default.(int64)
	// taskDescCompletionTokens is the schema descriptor for completion_tokens field.
	taskDescCompletionTokens := taskFields[9].Descriptor()
	// task.DefaultCompletionTokens holds the default value on creation for the completion_tokens field.
	task.DefaultCompletionTokens = taskDescCompletionTokens.Default.(int64)
	// taskDescOwnerPid is the schema descriptor for owner_pid field.
	taskDescOwnerPid := taskFields[10].Descriptor()
	// task.DefaultOwnerPid holds the default value on creation for the owner_pid field.
	task.DefaultOwnerPid = taskDescOwnerPid.Default.(int)
	// taskDescPriority is the schema descriptor for priority field.
	taskDescPriority := taskFields[11].Descriptor()
	// task.DefaultPriority holds the default value on creation for the priority field.
	task.DefaultPriority = taskDescPriority.Default.(int)
	// taskDescHandoffDepth is the schema descriptor for handoff_depth field.
	taskDescHandoffDepth := taskFields[12].Descriptor()
	// task.DefaultHandoffDepth holds the default value on creation for the handoff_depth field.
	task.DefaultHandoffDepth = taskDescHandoffDepth.Default.(int)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[15].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	wikipageFields := schema.WikiPage{}.Fields()
	_ = wikipageFields
	// wikipageDescSlug is the schema descriptor for slug field.
	wikipageDescSlug := wikipageFields[0].Descriptor()
	// wikipage.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	wikipage.SlugValidator = wikipageDescSlug.Validators[0].(func(string) error)
	// wikipageDescTitle is the schema descriptor for title field.
	wikipageDescTitle := wikipageFields[1].Descriptor()
	// wikipage.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	wikipage.TitleValidator = wikipageDescTitle.Validators[0].(func(string) error)
	// wikipageDescContent is the schema descriptor for content field.
	wikipageDescContent := wikipageFields[2].Descriptor()
	// wikipage.DefaultContent holds the default value on creation for the content field.
	wikipage.DefaultContent = wikipageDescContent.Default.(string)
	// wikipageDescAutoGenerated is the schema descriptor for auto_generated field.
	wikipageDescAutoGenerated := wikipageFields[4].Descriptor()
	// wikipage.DefaultAutoGenerated holds the default value on creation for the auto_generated field.
	wikipage.DefaultAutoGenerated = wikipageDescAutoGenerated.Default.(bool)
	// wikipageDescCreatedAt is the schema descriptor for created_at field.
	wikipageDescCreatedAt := wikipageFields[7].Descriptor()
	// wikipage.DefaultCreatedAt holds the default value on creation for the created_at field.
	wikipage.DefaultCreatedAt = wikipageDescCreatedAt.Default.(func() time.Time)
	// wikipageDescUpdatedAt is the schema descriptor for updated_at field.
	wikipageDescUpdatedAt := wikipageFields[8].Descriptor()
	// wikipage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	wikipage.DefaultUpdatedAt = wikipageDescUpdatedAt.Default.(func() time.Time)
	// wikipage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	wikipage.UpdateDefaultUpdatedAt = wikipageDescUpdatedAt.UpdateDefault.(func() time.Time)
	wikipageversionFields := schema.WikiPageVersion{}.Fields()
	_ = wikipageversionFields
	// wikipageversionDescPageSlug is the schema descriptor for page_slug field.
	wikipageversionDescPageSlug := wikipageversionFields[0].Descriptor()
	// wikipageversion.PageSlugValidator is a validator for the "page_slug" field. It is called by the builders before save.
	wikipageversion.PageSlugValidator = wikipageversionDescPageSlug.Validators[0].(func(string) error)
	// wikipageversionDescContent is the schema descriptor for content field.
	wikipageversionDescContent := wikipageversionFields[1].Descriptor()
	// wikipageversion.DefaultContent holds the default value on creation for the content field.
	wikipageversion.DefaultContent = wikipageversionDescContent.Default.(string)
	// wikipageversionDescSummary is the schema descriptor for summary field.
	wikipageversionDescSummary := wikipageversionFields[2].Descriptor()
	// wikipageversion.DefaultSummary holds the default value on creation for the summary field.
	wikipageversion.DefaultSummary = wikipageversionDescSummary.Default.(string)
	// wikipageversionDescAuthor is the schema descriptor for author field.
	wikipageversionDescAuthor := wikipageversionFields[3].Descriptor()
	// wikipageversion.DefaultAuthor holds the default value on creation for the author field.
	wikipageversion.DefaultAuthor = wikipageversionDescAuthor.Default.(string)
	// wikipageversionDescCreatedAt is the schema descriptor for created_at field.
	wikipageversionDescCreatedAt := wikipageversionFields[4].Descriptor()
	// wikipageversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	wikipageversion.DefaultCreatedAt = wikipageversionDescCreatedAt.Default.(func() time.Time)
}
