// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agurrrrr/shepherd/ent/predicate"
	"github.com/agurrrrr/shepherd/ent/project"
	"github.com/agurrrrr/shepherd/ent/schedule"
)

// ScheduleUpdate is the builder for updating Schedule entities.
type ScheduleUpdate struct {
	config
	hooks    []Hook
	mutation *ScheduleMutation
}

// Where appends a list predicates to the ScheduleUpdate builder.
func (_u *ScheduleUpdate) Where(ps ...predicate.Schedule) *ScheduleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ScheduleUpdate) SetName(v string) *ScheduleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableName(v *string) *ScheduleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *ScheduleUpdate) SetPrompt(v string) *ScheduleUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillablePrompt(v *string) *ScheduleUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetScheduleType sets the "schedule_type" field.
func (_u *ScheduleUpdate) SetScheduleType(v schedule.ScheduleType) *ScheduleUpdate {
	_u.mutation.SetScheduleType(v)
	return _u
}

// SetNillableScheduleType sets the "schedule_type" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableScheduleType(v *schedule.ScheduleType) *ScheduleUpdate {
	if v != nil {
		_u.SetScheduleType(*v)
	}
	return _u
}

// SetCronExpr sets the "cron_expr" field.
func (_u *ScheduleUpdate) SetCronExpr(v string) *ScheduleUpdate {
	_u.mutation.SetCronExpr(v)
	return _u
}

// SetNillableCronExpr sets the "cron_expr" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableCronExpr(v *string) *ScheduleUpdate {
	if v != nil {
		_u.SetCronExpr(*v)
	}
	return _u
}

// ClearCronExpr clears the value of the "cron_expr" field.
func (_u *ScheduleUpdate) ClearCronExpr() *ScheduleUpdate {
	_u.mutation.ClearCronExpr()
	return _u
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_u *ScheduleUpdate) SetIntervalSeconds(v int) *ScheduleUpdate {
	_u.mutation.ResetIntervalSeconds()
	_u.mutation.SetIntervalSeconds(v)
	return _u
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableIntervalSeconds(v *int) *ScheduleUpdate {
	if v != nil {
		_u.SetIntervalSeconds(*v)
	}
	return _u
}

// AddIntervalSeconds adds value to the "interval_seconds" field.
func (_u *ScheduleUpdate) AddIntervalSeconds(v int) *ScheduleUpdate {
	_u.mutation.AddIntervalSeconds(v)
	return _u
}

// ClearIntervalSeconds clears the value of the "interval_seconds" field.
func (_u *ScheduleUpdate) ClearIntervalSeconds() *ScheduleUpdate {
	_u.mutation.ClearIntervalSeconds()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ScheduleUpdate) SetEnabled(v bool) *ScheduleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableEnabled(v *bool) *ScheduleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLastRun sets the "last_run" field.
func (_u *ScheduleUpdate) SetLastRun(v time.Time) *ScheduleUpdate {
	_u.mutation.SetLastRun(v)
	return _u
}

// SetNillableLastRun sets the "last_run" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableLastRun(v *time.Time) *ScheduleUpdate {
	if v != nil {
		_u.SetLastRun(*v)
	}
	return _u
}

// ClearLastRun clears the value of the "last_run" field.
func (_u *ScheduleUpdate) ClearLastRun() *ScheduleUpdate {
	_u.mutation.ClearLastRun()
	return _u
}

// SetNextRun sets the "next_run" field.
func (_u *ScheduleUpdate) SetNextRun(v time.Time) *ScheduleUpdate {
	_u.mutation.SetNextRun(v)
	return _u
}

// SetNillableNextRun sets the "next_run" field if the given value is not nil.
func (_u *ScheduleUpdate) SetNillableNextRun(v *time.Time) *ScheduleUpdate {
	if v != nil {
		_u.SetNextRun(*v)
	}
	return _u
}

// ClearNextRun clears the value of the "next_run" field.
func (_u *ScheduleUpdate) ClearNextRun() *ScheduleUpdate {
	_u.mutation.ClearNextRun()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScheduleUpdate) SetUpdatedAt(v time.Time) *ScheduleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *ScheduleUpdate) SetProjectID(id int) *ScheduleUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ScheduleUpdate) SetProject(v *Project) *ScheduleUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ScheduleMutation object of the builder.
func (_u *ScheduleUpdate) Mutation() *ScheduleMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ScheduleUpdate) ClearProject() *ScheduleUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScheduleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScheduleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScheduleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := schedule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := schedule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Schedule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prompt(); ok {
		if err := schedule.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "Schedule.prompt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScheduleType(); ok {
		if err := schedule.ScheduleTypeValidator(v); err != nil {
			return &ValidationError{Name: "schedule_type", err: fmt.Errorf(`ent: validator failed for field "Schedule.schedule_type": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Schedule.project"`)
	}
	return nil
}

func (_u *ScheduleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedule.Table, schedule.Columns, sqlgraph.NewFieldSpec(schedule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(schedule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(schedule.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScheduleType(); ok {
		_spec.SetField(schedule.FieldScheduleType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CronExpr(); ok {
		_spec.SetField(schedule.FieldCronExpr, field.TypeString, value)
	}
	if _u.mutation.CronExprCleared() {
		_spec.ClearField(schedule.FieldCronExpr, field.TypeString)
	}
	if value, ok := _u.mutation.IntervalSeconds(); ok {
		_spec.SetField(schedule.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalSeconds(); ok {
		_spec.AddField(schedule.FieldIntervalSeconds, field.TypeInt, value)
	}
	if _u.mutation.IntervalSecondsCleared() {
		_spec.ClearField(schedule.FieldIntervalSeconds, field.TypeInt)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(schedule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastRun(); ok {
		_spec.SetField(schedule.FieldLastRun, field.TypeTime, value)
	}
	if _u.mutation.LastRunCleared() {
		_spec.ClearField(schedule.FieldLastRun, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRun(); ok {
		_spec.SetField(schedule.FieldNextRun, field.TypeTime, value)
	}
	if _u.mutation.NextRunCleared() {
		_spec.ClearField(schedule.FieldNextRun, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(schedule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.ProjectTable,
			Columns: []string{schedule.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.ProjectTable,
			Columns: []string{schedule.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScheduleUpdateOne is the builder for updating a single Schedule entity.
type ScheduleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScheduleMutation
}

// SetName sets the "name" field.
func (_u *ScheduleUpdateOne) SetName(v string) *ScheduleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableName(v *string) *ScheduleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *ScheduleUpdateOne) SetPrompt(v string) *ScheduleUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillablePrompt(v *string) *ScheduleUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetScheduleType sets the "schedule_type" field.
func (_u *ScheduleUpdateOne) SetScheduleType(v schedule.ScheduleType) *ScheduleUpdateOne {
	_u.mutation.SetScheduleType(v)
	return _u
}

// SetNillableScheduleType sets the "schedule_type" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableScheduleType(v *schedule.ScheduleType) *ScheduleUpdateOne {
	if v != nil {
		_u.SetScheduleType(*v)
	}
	return _u
}

// SetCronExpr sets the "cron_expr" field.
func (_u *ScheduleUpdateOne) SetCronExpr(v string) *ScheduleUpdateOne {
	_u.mutation.SetCronExpr(v)
	return _u
}

// SetNillableCronExpr sets the "cron_expr" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableCronExpr(v *string) *ScheduleUpdateOne {
	if v != nil {
		_u.SetCronExpr(*v)
	}
	return _u
}

// ClearCronExpr clears the value of the "cron_expr" field.
func (_u *ScheduleUpdateOne) ClearCronExpr() *ScheduleUpdateOne {
	_u.mutation.ClearCronExpr()
	return _u
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_u *ScheduleUpdateOne) SetIntervalSeconds(v int) *ScheduleUpdateOne {
	_u.mutation.ResetIntervalSeconds()
	_u.mutation.SetIntervalSeconds(v)
	return _u
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableIntervalSeconds(v *int) *ScheduleUpdateOne {
	if v != nil {
		_u.SetIntervalSeconds(*v)
	}
	return _u
}

// AddIntervalSeconds adds value to the "interval_seconds" field.
func (_u *ScheduleUpdateOne) AddIntervalSeconds(v int) *ScheduleUpdateOne {
	_u.mutation.AddIntervalSeconds(v)
	return _u
}

// ClearIntervalSeconds clears the value of the "interval_seconds" field.
func (_u *ScheduleUpdateOne) ClearIntervalSeconds() *ScheduleUpdateOne {
	_u.mutation.ClearIntervalSeconds()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ScheduleUpdateOne) SetEnabled(v bool) *ScheduleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableEnabled(v *bool) *ScheduleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLastRun sets the "last_run" field.
func (_u *ScheduleUpdateOne) SetLastRun(v time.Time) *ScheduleUpdateOne {
	_u.mutation.SetLastRun(v)
	return _u
}

// SetNillableLastRun sets the "last_run" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableLastRun(v *time.Time) *ScheduleUpdateOne {
	if v != nil {
		_u.SetLastRun(*v)
	}
	return _u
}

// ClearLastRun clears the value of the "last_run" field.
func (_u *ScheduleUpdateOne) ClearLastRun() *ScheduleUpdateOne {
	_u.mutation.ClearLastRun()
	return _u
}

// SetNextRun sets the "next_run" field.
func (_u *ScheduleUpdateOne) SetNextRun(v time.Time) *ScheduleUpdateOne {
	_u.mutation.SetNextRun(v)
	return _u
}

// SetNillableNextRun sets the "next_run" field if the given value is not nil.
func (_u *ScheduleUpdateOne) SetNillableNextRun(v *time.Time) *ScheduleUpdateOne {
	if v != nil {
		_u.SetNextRun(*v)
	}
	return _u
}

// ClearNextRun clears the value of the "next_run" field.
func (_u *ScheduleUpdateOne) ClearNextRun() *ScheduleUpdateOne {
	_u.mutation.ClearNextRun()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScheduleUpdateOne) SetUpdatedAt(v time.Time) *ScheduleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *ScheduleUpdateOne) SetProjectID(id int) *ScheduleUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ScheduleUpdateOne) SetProject(v *Project) *ScheduleUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ScheduleMutation object of the builder.
func (_u *ScheduleUpdateOne) Mutation() *ScheduleMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ScheduleUpdateOne) ClearProject() *ScheduleUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the ScheduleUpdate builder.
func (_u *ScheduleUpdateOne) Where(ps ...predicate.Schedule) *ScheduleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScheduleUpdateOne) Select(field string, fields ...string) *ScheduleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Schedule entity.
func (_u *ScheduleUpdateOne) Save(ctx context.Context) (*Schedule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScheduleUpdateOne) SaveX(ctx context.Context) *Schedule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScheduleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScheduleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScheduleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := schedule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScheduleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := schedule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Schedule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prompt(); ok {
		if err := schedule.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "Schedule.prompt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScheduleType(); ok {
		if err := schedule.ScheduleTypeValidator(v); err != nil {
			return &ValidationError{Name: "schedule_type", err: fmt.Errorf(`ent: validator failed for field "Schedule.schedule_type": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Schedule.project"`)
	}
	return nil
}

func (_u *ScheduleUpdateOne) sqlSave(ctx context.Context) (_node *Schedule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schedule.Table, schedule.Columns, sqlgraph.NewFieldSpec(schedule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Schedule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schedule.FieldID)
		for _, f := range fields {
			if !schedule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schedule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(schedule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(schedule.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScheduleType(); ok {
		_spec.SetField(schedule.FieldScheduleType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CronExpr(); ok {
		_spec.SetField(schedule.FieldCronExpr, field.TypeString, value)
	}
	if _u.mutation.CronExprCleared() {
		_spec.ClearField(schedule.FieldCronExpr, field.TypeString)
	}
	if value, ok := _u.mutation.IntervalSeconds(); ok {
		_spec.SetField(schedule.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalSeconds(); ok {
		_spec.AddField(schedule.FieldIntervalSeconds, field.TypeInt, value)
	}
	if _u.mutation.IntervalSecondsCleared() {
		_spec.ClearField(schedule.FieldIntervalSeconds, field.TypeInt)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(schedule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastRun(); ok {
		_spec.SetField(schedule.FieldLastRun, field.TypeTime, value)
	}
	if _u.mutation.LastRunCleared() {
		_spec.ClearField(schedule.FieldLastRun, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRun(); ok {
		_spec.SetField(schedule.FieldNextRun, field.TypeTime, value)
	}
	if _u.mutation.NextRunCleared() {
		_spec.ClearField(schedule.FieldNextRun, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(schedule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.ProjectTable,
			Columns: []string{schedule.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   schedule.ProjectTable,
			Columns: []string{schedule.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Schedule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
