// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agurrrrr/shepherd/ent/sheepname"
)

// SheepNameCreate is the builder for creating a SheepName entity.
type SheepNameCreate struct {
	config
	mutation *SheepNameMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *SheepNameCreate) SetName(v string) *SheepNameCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *SheepNameCreate) SetPriority(v int) *SheepNameCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *SheepNameCreate) SetNillablePriority(v *int) *SheepNameCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SheepNameCreate) SetCreatedAt(v time.Time) *SheepNameCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SheepNameCreate) SetNillableCreatedAt(v *time.Time) *SheepNameCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the SheepNameMutation object of the builder.
func (_c *SheepNameCreate) Mutation() *SheepNameMutation {
	return _c.mutation
}

// Save creates the SheepName in the database.
func (_c *SheepNameCreate) Save(ctx context.Context) (*SheepName, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SheepNameCreate) SaveX(ctx context.Context) *SheepName {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SheepNameCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SheepNameCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SheepNameCreate) defaults() {
	if _, ok := _c.mutation.Priority(); !ok {
		v := sheepname.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sheepname.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SheepNameCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SheepName.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := sheepname.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SheepName.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "SheepName.priority"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SheepName.created_at"`)}
	}
	return nil
}

func (_c *SheepNameCreate) sqlSave(ctx context.Context) (*SheepName, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SheepNameCreate) createSpec() (*SheepName, *sqlgraph.CreateSpec) {
	var (
		_node = &SheepName{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sheepname.Table, sqlgraph.NewFieldSpec(sheepname.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(sheepname.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(sheepname.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sheepname.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// SheepNameCreateBulk is the builder for creating many SheepName entities in bulk.
type SheepNameCreateBulk struct {
	config
	err      error
	builders []*SheepNameCreate
}

// Save creates the SheepName entities in the database.
func (_c *SheepNameCreateBulk) Save(ctx context.Context) ([]*SheepName, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SheepName, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SheepNameMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SheepNameCreateBulk) SaveX(ctx context.Context) []*SheepName {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SheepNameCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SheepNameCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
