// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agurrrrr/shepherd/ent/predicate"
	"github.com/agurrrrr/shepherd/ent/sheepname"
)

// SheepNameUpdate is the builder for updating SheepName entities.
type SheepNameUpdate struct {
	config
	hooks    []Hook
	mutation *SheepNameMutation
}

// Where appends a list predicates to the SheepNameUpdate builder.
func (_u *SheepNameUpdate) Where(ps ...predicate.SheepName) *SheepNameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SheepNameUpdate) SetName(v string) *SheepNameUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SheepNameUpdate) SetNillableName(v *string) *SheepNameUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SheepNameUpdate) SetPriority(v int) *SheepNameUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SheepNameUpdate) SetNillablePriority(v *int) *SheepNameUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *SheepNameUpdate) AddPriority(v int) *SheepNameUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// Mutation returns the SheepNameMutation object of the builder.
func (_u *SheepNameUpdate) Mutation() *SheepNameMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SheepNameUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SheepNameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SheepNameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SheepNameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SheepNameUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := sheepname.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SheepName.name": %w`, err)}
		}
	}
	return nil
}

func (_u *SheepNameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sheepname.Table, sheepname.Columns, sqlgraph.NewFieldSpec(sheepname.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sheepname.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(sheepname.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(sheepname.FieldPriority, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sheepname.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SheepNameUpdateOne is the builder for updating a single SheepName entity.
type SheepNameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SheepNameMutation
}

// SetName sets the "name" field.
func (_u *SheepNameUpdateOne) SetName(v string) *SheepNameUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SheepNameUpdateOne) SetNillableName(v *string) *SheepNameUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SheepNameUpdateOne) SetPriority(v int) *SheepNameUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SheepNameUpdateOne) SetNillablePriority(v *int) *SheepNameUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *SheepNameUpdateOne) AddPriority(v int) *SheepNameUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// Mutation returns the SheepNameMutation object of the builder.
func (_u *SheepNameUpdateOne) Mutation() *SheepNameMutation {
	return _u.mutation
}

// Where appends a list predicates to the SheepNameUpdate builder.
func (_u *SheepNameUpdateOne) Where(ps ...predicate.SheepName) *SheepNameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SheepNameUpdateOne) Select(field string, fields ...string) *SheepNameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SheepName entity.
func (_u *SheepNameUpdateOne) Save(ctx context.Context) (*SheepName, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SheepNameUpdateOne) SaveX(ctx context.Context) *SheepName {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SheepNameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SheepNameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SheepNameUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := sheepname.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SheepName.name": %w`, err)}
		}
	}
	return nil
}

func (_u *SheepNameUpdateOne) sqlSave(ctx context.Context) (_node *SheepName, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sheepname.Table, sheepname.Columns, sqlgraph.NewFieldSpec(sheepname.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SheepName.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sheepname.FieldID)
		for _, f := range fields {
			if !sheepname.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sheepname.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sheepname.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(sheepname.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(sheepname.FieldPriority, field.TypeInt, value)
	}
	_node = &SheepName{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sheepname.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
