// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/agurrrrr/shepherd/ent/sheepname"
)

// SheepName is the model entity for the SheepName schema.
type SheepName struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 양 이름
	Name string `json:"name,omitempty"`
	// 우선순위 (낮을수록 먼저 사용)
	Priority int `json:"priority,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SheepName) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sheepname.FieldID, sheepname.FieldPriority:
			values[i] = new(sql.NullInt64)
		case sheepname.FieldName:
			values[i] = new(sql.NullString)
		case sheepname.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SheepName fields.
func (_m *SheepName) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sheepname.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case sheepname.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case sheepname.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case sheepname.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SheepName.
// This includes values selected through modifiers, order, etc.
func (_m *SheepName) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SheepName.
// Note that you need to call SheepName.Unwrap() before calling this method if this SheepName
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SheepName) Update() *SheepNameUpdateOne {
	return NewSheepNameClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SheepName entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SheepName) Unwrap() *SheepName {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SheepName is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SheepName) String() string {
	var builder strings.Builder
	builder.WriteString("SheepName(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SheepNames is a parsable slice of SheepName.
type SheepNames []*SheepName
