// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agurrrrr/shepherd/ent/browsersession"
	"github.com/agurrrrr/shepherd/ent/predicate"
	"github.com/agurrrrr/shepherd/ent/project"
	"github.com/agurrrrr/shepherd/ent/sheep"
	"github.com/agurrrrr/shepherd/ent/task"
)

// SheepUpdate is the builder for updating Sheep entities.
type SheepUpdate struct {
	config
	hooks    []Hook
	mutation *SheepMutation
}

// Where appends a list predicates to the SheepUpdate builder.
func (_u *SheepUpdate) Where(ps ...predicate.Sheep) *SheepUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SheepUpdate) SetName(v string) *SheepUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SheepUpdate) SetNillableName(v *string) *SheepUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SheepUpdate) SetStatus(v sheep.Status) *SheepUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SheepUpdate) SetNillableStatus(v *sheep.Status) *SheepUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *SheepUpdate) SetSessionID(v string) *SheepUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *SheepUpdate) SetNillableSessionID(v *string) *SheepUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *SheepUpdate) ClearSessionID() *SheepUpdate {
	_u.mutation.ClearSessionID()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *SheepUpdate) SetProvider(v sheep.Provider) *SheepUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *SheepUpdate) SetNillableProvider(v *sheep.Provider) *SheepUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *SheepUpdate) SetConsecutiveFailures(v int) *SheepUpdate {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *SheepUpdate) SetNillableConsecutiveFailures(v *int) *SheepUpdate {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *SheepUpdate) AddConsecutiveFailures(v int) *SheepUpdate {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SheepUpdate) SetUpdatedAt(v time.Time) *SheepUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *SheepUpdate) SetProjectID(id int) *SheepUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_u *SheepUpdate) SetNillableProjectID(id *int) *SheepUpdate {
	if id != nil {
		_u = _u.SetProjectID(*id)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *SheepUpdate) SetProject(v *Project) *SheepUpdate {
	return _u.SetProjectID(v.ID)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *SheepUpdate) AddTaskIDs(ids ...int) *SheepUpdate {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *SheepUpdate) AddTasks(v ...*Task) *SheepUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// SetBrowserSessionID sets the "browser_session" edge to the BrowserSession entity by ID.
func (_u *SheepUpdate) SetBrowserSessionID(id int) *SheepUpdate {
	_u.mutation.SetBrowserSessionID(id)
	return _u
}

// SetNillableBrowserSessionID sets the "browser_session" edge to the BrowserSession entity by ID if the given value is not nil.
func (_u *SheepUpdate) SetNillableBrowserSessionID(id *int) *SheepUpdate {
	if id != nil {
		_u = _u.SetBrowserSessionID(*id)
	}
	return _u
}

// SetBrowserSession sets the "browser_session" edge to the BrowserSession entity.
func (_u *SheepUpdate) SetBrowserSession(v *BrowserSession) *SheepUpdate {
	return _u.SetBrowserSessionID(v.ID)
}

// Mutation returns the SheepMutation object of the builder.
func (_u *SheepUpdate) Mutation() *SheepMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *SheepUpdate) ClearProject() *SheepUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *SheepUpdate) ClearTasks() *SheepUpdate {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *SheepUpdate) RemoveTaskIDs(ids ...int) *SheepUpdate {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *SheepUpdate) RemoveTasks(v ...*Task) *SheepUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// ClearBrowserSession clears the "browser_session" edge to the BrowserSession entity.
func (_u *SheepUpdate) ClearBrowserSession() *SheepUpdate {
	_u.mutation.ClearBrowserSession()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SheepUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SheepUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SheepUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SheepUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SheepUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sheep.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SheepUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := sheep.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Sheep.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sheep.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Sheep.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := sheep.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Sheep.provider": %w`, err)}
		}
	}
	return nil
}

func (_u *SheepUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sheep.Table, sheep.Columns, sqlgraph.NewFieldSpec(sheep.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sheep.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sheep.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(sheep.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(sheep.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(sheep.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(sheep.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(sheep.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sheep.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sheep.ProjectTable,
			Columns: []string{sheep.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sheep.ProjectTable,
			Columns: []string{sheep.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sheep.TasksTable,
			Columns: []string{sheep.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sheep.TasksTable,
			Columns: []string{sheep.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sheep.TasksTable,
			Columns: []string{sheep.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BrowserSessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sheep.BrowserSessionTable,
			Columns: []string{sheep.BrowserSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(browsersession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BrowserSessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sheep.BrowserSessionTable,
			Columns: []string{sheep.BrowserSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(browsersession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sheep.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SheepUpdateOne is the builder for updating a single Sheep entity.
type SheepUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SheepMutation
}

// SetName sets the "name" field.
func (_u *SheepUpdateOne) SetName(v string) *SheepUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SheepUpdateOne) SetNillableName(v *string) *SheepUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SheepUpdateOne) SetStatus(v sheep.Status) *SheepUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SheepUpdateOne) SetNillableStatus(v *sheep.Status) *SheepUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *SheepUpdateOne) SetSessionID(v string) *SheepUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *SheepUpdateOne) SetNillableSessionID(v *string) *SheepUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *SheepUpdateOne) ClearSessionID() *SheepUpdateOne {
	_u.mutation.ClearSessionID()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *SheepUpdateOne) SetProvider(v sheep.Provider) *SheepUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *SheepUpdateOne) SetNillableProvider(v *sheep.Provider) *SheepUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *SheepUpdateOne) SetConsecutiveFailures(v int) *SheepUpdateOne {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *SheepUpdateOne) SetNillableConsecutiveFailures(v *int) *SheepUpdateOne {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *SheepUpdateOne) AddConsecutiveFailures(v int) *SheepUpdateOne {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SheepUpdateOne) SetUpdatedAt(v time.Time) *SheepUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *SheepUpdateOne) SetProjectID(id int) *SheepUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_u *SheepUpdateOne) SetNillableProjectID(id *int) *SheepUpdateOne {
	if id != nil {
		_u = _u.SetProjectID(*id)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *SheepUpdateOne) SetProject(v *Project) *SheepUpdateOne {
	return _u.SetProjectID(v.ID)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *SheepUpdateOne) AddTaskIDs(ids ...int) *SheepUpdateOne {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *SheepUpdateOne) AddTasks(v ...*Task) *SheepUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// SetBrowserSessionID sets the "browser_session" edge to the BrowserSession entity by ID.
func (_u *SheepUpdateOne) SetBrowserSessionID(id int) *SheepUpdateOne {
	_u.mutation.SetBrowserSessionID(id)
	return _u
}

// SetNillableBrowserSessionID sets the "browser_session" edge to the BrowserSession entity by ID if the given value is not nil.
func (_u *SheepUpdateOne) SetNillableBrowserSessionID(id *int) *SheepUpdateOne {
	if id != nil {
		_u = _u.SetBrowserSessionID(*id)
	}
	return _u
}

// SetBrowserSession sets the "browser_session" edge to the BrowserSession entity.
func (_u *SheepUpdateOne) SetBrowserSession(v *BrowserSession) *SheepUpdateOne {
	return _u.SetBrowserSessionID(v.ID)
}

// Mutation returns the SheepMutation object of the builder.
func (_u *SheepUpdateOne) Mutation() *SheepMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *SheepUpdateOne) ClearProject() *SheepUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *SheepUpdateOne) ClearTasks() *SheepUpdateOne {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *SheepUpdateOne) RemoveTaskIDs(ids ...int) *SheepUpdateOne {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *SheepUpdateOne) RemoveTasks(v ...*Task) *SheepUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// ClearBrowserSession clears the "browser_session" edge to the BrowserSession entity.
func (_u *SheepUpdateOne) ClearBrowserSession() *SheepUpdateOne {
	_u.mutation.ClearBrowserSession()
	return _u
}

// Where appends a list predicates to the SheepUpdate builder.
func (_u *SheepUpdateOne) Where(ps ...predicate.Sheep) *SheepUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SheepUpdateOne) Select(field string, fields ...string) *SheepUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Sheep entity.
func (_u *SheepUpdateOne) Save(ctx context.Context) (*Sheep, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SheepUpdateOne) SaveX(ctx context.Context) *Sheep {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SheepUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SheepUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SheepUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sheep.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SheepUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := sheep.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Sheep.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sheep.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Sheep.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := sheep.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Sheep.provider": %w`, err)}
		}
	}
	return nil
}

func (_u *SheepUpdateOne) sqlSave(ctx context.Context) (_node *Sheep, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sheep.Table, sheep.Columns, sqlgraph.NewFieldSpec(sheep.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sheep.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sheep.FieldID)
		for _, f := range fields {
			if !sheep.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sheep.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sheep.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sheep.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(sheep.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(sheep.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(sheep.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(sheep.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(sheep.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sheep.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sheep.ProjectTable,
			Columns: []string{sheep.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sheep.ProjectTable,
			Columns: []string{sheep.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sheep.TasksTable,
			Columns: []string{sheep.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sheep.TasksTable,
			Columns: []string{sheep.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sheep.TasksTable,
			Columns: []string{sheep.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BrowserSessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sheep.BrowserSessionTable,
			Columns: []string{sheep.BrowserSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(browsersession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BrowserSessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sheep.BrowserSessionTable,
			Columns: []string{sheep.BrowserSessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(browsersession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Sheep{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sheep.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
