// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/agurrrrr/shepherd/ent/browsersession"
	"github.com/agurrrrr/shepherd/ent/project"
	"github.com/agurrrrr/shepherd/ent/sheep"
)

// Sheep is the model entity for the Sheep schema.
type Sheep struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 양 이름 (양동이, 양말이 등)
	Name string `json:"name,omitempty"`
	// 양 상태
	Status sheep.Status `json:"status,omitempty"`
	// Claude Code 세션 ID
	SessionID string `json:"session_id,omitempty"`
	// AI provider (claude, opencode, auto)
	Provider sheep.Provider `json:"provider,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SheepQuery when eager-loading is set.
	Edges         SheepEdges `json:"edges"`
	project_sheep *int
	selectValues  sql.SelectValues
}

// SheepEdges holds the relations/edges for other nodes in the graph.
type SheepEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Tasks holds the value of the tasks edge.
	Tasks []*Task `json:"tasks,omitempty"`
	// BrowserSession holds the value of the browser_session edge.
	BrowserSession *BrowserSession `json:"browser_session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SheepEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// TasksOrErr returns the Tasks value or an error if the edge
// was not loaded in eager-loading.
func (e SheepEdges) TasksOrErr() ([]*Task, error) {
	if e.loadedTypes[1] {
		return e.Tasks, nil
	}
	return nil, &NotLoadedError{edge: "tasks"}
}

// BrowserSessionOrErr returns the BrowserSession value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SheepEdges) BrowserSessionOrErr() (*BrowserSession, error) {
	if e.BrowserSession != nil {
		return e.BrowserSession, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: browsersession.Label}
	}
	return nil, &NotLoadedError{edge: "browser_session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Sheep) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sheep.FieldID:
			values[i] = new(sql.NullInt64)
		case sheep.FieldName, sheep.FieldStatus, sheep.FieldSessionID, sheep.FieldProvider:
			values[i] = new(sql.NullString)
		case sheep.FieldCreatedAt, sheep.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case sheep.ForeignKeys[0]: // project_sheep
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Sheep fields.
func (_m *Sheep) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sheep.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case sheep.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case sheep.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = sheep.Status(value.String)
			}
		case sheep.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case sheep.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = sheep.Provider(value.String)
			}
		case sheep.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sheep.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sheep.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field project_sheep", value)
			} else if value.Valid {
				_m.project_sheep = new(int)
				*_m.project_sheep = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Sheep.
// This includes values selected through modifiers, order, etc.
func (_m *Sheep) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Sheep entity.
func (_m *Sheep) QueryProject() *ProjectQuery {
	return NewSheepClient(_m.config).QueryProject(_m)
}

// QueryTasks queries the "tasks" edge of the Sheep entity.
func (_m *Sheep) QueryTasks() *TaskQuery {
	return NewSheepClient(_m.config).QueryTasks(_m)
}

// QueryBrowserSession queries the "browser_session" edge of the Sheep entity.
func (_m *Sheep) QueryBrowserSession() *BrowserSessionQuery {
	return NewSheepClient(_m.config).QueryBrowserSession(_m)
}

// Update returns a builder for updating this Sheep.
// Note that you need to call Sheep.Unwrap() before calling this method if this Sheep
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Sheep) Update() *SheepUpdateOne {
	return NewSheepClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Sheep entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Sheep) Unwrap() *Sheep {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Sheep is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Sheep) String() string {
	var builder strings.Builder
	builder.WriteString("Sheep(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(fmt.Sprintf("%v", _m.Provider))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SheepSlice is a parsable slice of Sheep.
type SheepSlice []*Sheep
