// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agurrrrr/shepherd/ent/project"
	"github.com/agurrrrr/shepherd/ent/skill"
)

// SkillCreate is the builder for creating a Skill entity.
type SkillCreate struct {
	config
	mutation *SkillMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *SkillCreate) SetName(v string) *SkillCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SkillCreate) SetDescription(v string) *SkillCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SkillCreate) SetNillableDescription(v *string) *SkillCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *SkillCreate) SetContent(v string) *SkillCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *SkillCreate) SetScope(v skill.Scope) *SkillCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *SkillCreate) SetNillableScope(v *skill.Scope) *SkillCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *SkillCreate) SetEnabled(v bool) *SkillCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *SkillCreate) SetNillableEnabled(v *bool) *SkillCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *SkillCreate) SetTags(v []string) *SkillCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetBundled sets the "bundled" field.
func (_c *SkillCreate) SetBundled(v bool) *SkillCreate {
	_c.mutation.SetBundled(v)
	return _c
}

// SetNillableBundled sets the "bundled" field if the given value is not nil.
func (_c *SkillCreate) SetNillableBundled(v *bool) *SkillCreate {
	if v != nil {
		_c.SetBundled(*v)
	}
	return _c
}

// SetEffort sets the "effort" field.
func (_c *SkillCreate) SetEffort(v string) *SkillCreate {
	_c.mutation.SetEffort(v)
	return _c
}

// SetNillableEffort sets the "effort" field if the given value is not nil.
func (_c *SkillCreate) SetNillableEffort(v *string) *SkillCreate {
	if v != nil {
		_c.SetEffort(*v)
	}
	return _c
}

// SetMaxTurns sets the "max_turns" field.
func (_c *SkillCreate) SetMaxTurns(v int) *SkillCreate {
	_c.mutation.SetMaxTurns(v)
	return _c
}

// SetNillableMaxTurns sets the "max_turns" field if the given value is not nil.
func (_c *SkillCreate) SetNillableMaxTurns(v *int) *SkillCreate {
	if v != nil {
		_c.SetMaxTurns(*v)
	}
	return _c
}

// SetDisallowedTools sets the "disallowed_tools" field.
func (_c *SkillCreate) SetDisallowedTools(v []string) *SkillCreate {
	_c.mutation.SetDisallowedTools(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SkillCreate) SetCreatedAt(v time.Time) *SkillCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SkillCreate) SetNillableCreatedAt(v *time.Time) *SkillCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SkillCreate) SetUpdatedAt(v time.Time) *SkillCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SkillCreate) SetNillableUpdatedAt(v *time.Time) *SkillCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_c *SkillCreate) SetProjectID(id int) *SkillCreate {
	_c.mutation.SetProjectID(id)
	return _c
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_c *SkillCreate) SetNillableProjectID(id *int) *SkillCreate {
	if id != nil {
		_c = _c.SetProjectID(*id)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *SkillCreate) SetProject(v *Project) *SkillCreate {
	return _c.SetProjectID(v.ID)
}

// Mutation returns the SkillMutation object of the builder.
func (_c *SkillCreate) Mutation() *SkillMutation {
	return _c.mutation
}

// Save creates the Skill in the database.
func (_c *SkillCreate) Save(ctx context.Context) (*Skill, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SkillCreate) SaveX(ctx context.Context) *Skill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SkillCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SkillCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SkillCreate) defaults() {
	if _, ok := _c.mutation.Scope(); !ok {
		v := skill.DefaultScope
		_c.mutation.SetScope(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := skill.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Bundled(); !ok {
		v := skill.DefaultBundled
		_c.mutation.SetBundled(v)
	}
	if _, ok := _c.mutation.Effort(); !ok {
		v := skill.DefaultEffort
		_c.mutation.SetEffort(v)
	}
	if _, ok := _c.mutation.MaxTurns(); !ok {
		v := skill.DefaultMaxTurns
		_c.mutation.SetMaxTurns(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := skill.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := skill.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SkillCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Skill.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := skill.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Skill.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Skill.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := skill.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Skill.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "Skill.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := skill.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Skill.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Skill.enabled"`)}
	}
	if _, ok := _c.mutation.Bundled(); !ok {
		return &ValidationError{Name: "bundled", err: errors.New(`ent: missing required field "Skill.bundled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Skill.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Skill.updated_at"`)}
	}
	return nil
}

func (_c *SkillCreate) sqlSave(ctx context.Context) (*Skill, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SkillCreate) createSpec() (*Skill, *sqlgraph.CreateSpec) {
	var (
		_node = &Skill{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(skill.Table, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(skill.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(skill.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(skill.FieldScope, field.TypeEnum, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(skill.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(skill.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.Bundled(); ok {
		_spec.SetField(skill.FieldBundled, field.TypeBool, value)
		_node.Bundled = value
	}
	if value, ok := _c.mutation.Effort(); ok {
		_spec.SetField(skill.FieldEffort, field.TypeString, value)
		_node.Effort = value
	}
	if value, ok := _c.mutation.MaxTurns(); ok {
		_spec.SetField(skill.FieldMaxTurns, field.TypeInt, value)
		_node.MaxTurns = value
	}
	if value, ok := _c.mutation.DisallowedTools(); ok {
		_spec.SetField(skill.FieldDisallowedTools, field.TypeJSON, value)
		_node.DisallowedTools = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(skill.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(skill.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skill.ProjectTable,
			Columns: []string{skill.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_skills = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SkillCreateBulk is the builder for creating many Skill entities in bulk.
type SkillCreateBulk struct {
	config
	err      error
	builders []*SkillCreate
}

// Save creates the Skill entities in the database.
func (_c *SkillCreateBulk) Save(ctx context.Context) ([]*Skill, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Skill, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SkillMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SkillCreateBulk) SaveX(ctx context.Context) []*Skill {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SkillCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SkillCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
