// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/agurrrrr/shepherd/ent/issue"
	"github.com/agurrrrr/shepherd/ent/project"
	"github.com/agurrrrr/shepherd/ent/sheep"
	"github.com/agurrrrr/shepherd/ent/task"
)

// Task is the model entity for the Task schema.
type Task struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 사용자 요청
	Prompt string `json:"prompt,omitempty"`
	// 작업 요약 (AI 생성)
	Summary string `json:"summary,omitempty"`
	// 수정한 파일 목록
	FilesModified []string `json:"files_modified,omitempty"`
	// 작업 상태
	Status task.Status `json:"status,omitempty"`
	// 에러 메시지
	Error string `json:"error,omitempty"`
	// 작업별 모델 오버라이드 (provider/model 형식, OpenCode 동시작업 그룹 집계에 사용)
	Model string `json:"model,omitempty"`
	// 작업 출력 로그
	Output []string `json:"output,omitempty"`
	// 실행 비용 (USD)
	CostUsd float64 `json:"cost_usd,omitempty"`
	// 입력 토큰 수
	PromptTokens int64 `json:"prompt_tokens,omitempty"`
	// 출력 토큰 수
	CompletionTokens int64 `json:"completion_tokens,omitempty"`
	// 작업을 실행 중인 프로세스 PID (소유권/생존 판별용)
	OwnerPid int `json:"owner_pid,omitempty"`
	// 작업 시작 시간
	StartedAt time.Time `json:"started_at,omitempty"`
	// 작업 완료 시간
	CompletedAt time.Time `json:"completed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskQuery when eager-loading is set.
	Edges         TaskEdges `json:"edges"`
	issue_tasks   *int
	project_tasks *int
	sheep_tasks   *int
	selectValues  sql.SelectValues
}

// TaskEdges holds the relations/edges for other nodes in the graph.
type TaskEdges struct {
	// Sheep holds the value of the sheep edge.
	Sheep *Sheep `json:"sheep,omitempty"`
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Issue holds the value of the issue edge.
	Issue *Issue `json:"issue,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// SheepOrErr returns the Sheep value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) SheepOrErr() (*Sheep, error) {
	if e.Sheep != nil {
		return e.Sheep, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: sheep.Label}
	}
	return nil, &NotLoadedError{edge: "sheep"}
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// IssueOrErr returns the Issue value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) IssueOrErr() (*Issue, error) {
	if e.Issue != nil {
		return e.Issue, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: issue.Label}
	}
	return nil, &NotLoadedError{edge: "issue"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Task) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case task.FieldFilesModified, task.FieldOutput:
			values[i] = new([]byte)
		case task.FieldCostUsd:
			values[i] = new(sql.NullFloat64)
		case task.FieldID, task.FieldPromptTokens, task.FieldCompletionTokens, task.FieldOwnerPid:
			values[i] = new(sql.NullInt64)
		case task.FieldPrompt, task.FieldSummary, task.FieldStatus, task.FieldError, task.FieldModel:
			values[i] = new(sql.NullString)
		case task.FieldStartedAt, task.FieldCompletedAt, task.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case task.ForeignKeys[0]: // issue_tasks
			values[i] = new(sql.NullInt64)
		case task.ForeignKeys[1]: // project_tasks
			values[i] = new(sql.NullInt64)
		case task.ForeignKeys[2]: // sheep_tasks
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Task fields.
func (_m *Task) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case task.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case task.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case task.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case task.FieldFilesModified:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field files_modified", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.FilesModified); err != nil {
					return fmt.Errorf("unmarshal field files_modified: %w", err)
				}
			}
		case task.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = task.Status(value.String)
			}
		case task.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case task.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case task.FieldOutput:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field output", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Output); err != nil {
					return fmt.Errorf("unmarshal field output: %w", err)
				}
			}
		case task.FieldCostUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_usd", values[i])
			} else if value.Valid {
				_m.CostUsd = value.Float64
			}
		case task.FieldPromptTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_tokens", values[i])
			} else if value.Valid {
				_m.PromptTokens = value.Int64
			}
		case task.FieldCompletionTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field completion_tokens", values[i])
			} else if value.Valid {
				_m.CompletionTokens = value.Int64
			}
		case task.FieldOwnerPid:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_pid", values[i])
			} else if value.Valid {
				_m.OwnerPid = int(value.Int64)
			}
		case task.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case task.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = value.Time
			}
		case task.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case task.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field issue_tasks", value)
			} else if value.Valid {
				_m.issue_tasks = new(int)
				*_m.issue_tasks = int(value.Int64)
			}
		case task.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field project_tasks", value)
			} else if value.Valid {
				_m.project_tasks = new(int)
				*_m.project_tasks = int(value.Int64)
			}
		case task.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field sheep_tasks", value)
			} else if value.Valid {
				_m.sheep_tasks = new(int)
				*_m.sheep_tasks = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Task.
// This includes values selected through modifiers, order, etc.
func (_m *Task) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySheep queries the "sheep" edge of the Task entity.
func (_m *Task) QuerySheep() *SheepQuery {
	return NewTaskClient(_m.config).QuerySheep(_m)
}

// QueryProject queries the "project" edge of the Task entity.
func (_m *Task) QueryProject() *ProjectQuery {
	return NewTaskClient(_m.config).QueryProject(_m)
}

// QueryIssue queries the "issue" edge of the Task entity.
func (_m *Task) QueryIssue() *IssueQuery {
	return NewTaskClient(_m.config).QueryIssue(_m)
}

// Update returns a builder for updating this Task.
// Note that you need to call Task.Unwrap() before calling this method if this Task
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Task) Update() *TaskUpdateOne {
	return NewTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Task entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Task) Unwrap() *Task {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Task is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Task) String() string {
	var builder strings.Builder
	builder.WriteString("Task(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("files_modified=")
	builder.WriteString(fmt.Sprintf("%v", _m.FilesModified))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("output=")
	builder.WriteString(fmt.Sprintf("%v", _m.Output))
	builder.WriteString(", ")
	builder.WriteString("cost_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostUsd))
	builder.WriteString(", ")
	builder.WriteString("prompt_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromptTokens))
	builder.WriteString(", ")
	builder.WriteString("completion_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompletionTokens))
	builder.WriteString(", ")
	builder.WriteString("owner_pid=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerPid))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("completed_at=")
	builder.WriteString(_m.CompletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Tasks is a parsable slice of Task.
type Tasks []*Task
