// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agurrrrr/shepherd/ent/project"
	"github.com/agurrrrr/shepherd/ent/wikipageversion"
)

// WikiPageVersionCreate is the builder for creating a WikiPageVersion entity.
type WikiPageVersionCreate struct {
	config
	mutation *WikiPageVersionMutation
	hooks    []Hook
}

// SetPageSlug sets the "page_slug" field.
func (_c *WikiPageVersionCreate) SetPageSlug(v string) *WikiPageVersionCreate {
	_c.mutation.SetPageSlug(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *WikiPageVersionCreate) SetContent(v string) *WikiPageVersionCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *WikiPageVersionCreate) SetNillableContent(v *string) *WikiPageVersionCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *WikiPageVersionCreate) SetSummary(v string) *WikiPageVersionCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *WikiPageVersionCreate) SetNillableSummary(v *string) *WikiPageVersionCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetAuthor sets the "author" field.
func (_c *WikiPageVersionCreate) SetAuthor(v string) *WikiPageVersionCreate {
	_c.mutation.SetAuthor(v)
	return _c
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_c *WikiPageVersionCreate) SetNillableAuthor(v *string) *WikiPageVersionCreate {
	if v != nil {
		_c.SetAuthor(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WikiPageVersionCreate) SetCreatedAt(v time.Time) *WikiPageVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WikiPageVersionCreate) SetNillableCreatedAt(v *time.Time) *WikiPageVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_c *WikiPageVersionCreate) SetProjectID(id int) *WikiPageVersionCreate {
	_c.mutation.SetProjectID(id)
	return _c
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_c *WikiPageVersionCreate) SetNillableProjectID(id *int) *WikiPageVersionCreate {
	if id != nil {
		_c = _c.SetProjectID(*id)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *WikiPageVersionCreate) SetProject(v *Project) *WikiPageVersionCreate {
	return _c.SetProjectID(v.ID)
}

// Mutation returns the WikiPageVersionMutation object of the builder.
func (_c *WikiPageVersionCreate) Mutation() *WikiPageVersionMutation {
	return _c.mutation
}

// Save creates the WikiPageVersion in the database.
func (_c *WikiPageVersionCreate) Save(ctx context.Context) (*WikiPageVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WikiPageVersionCreate) SaveX(ctx context.Context) *WikiPageVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WikiPageVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WikiPageVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WikiPageVersionCreate) defaults() {
	if _, ok := _c.mutation.Content(); !ok {
		v := wikipageversion.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.Summary(); !ok {
		v := wikipageversion.DefaultSummary
		_c.mutation.SetSummary(v)
	}
	if _, ok := _c.mutation.Author(); !ok {
		v := wikipageversion.DefaultAuthor
		_c.mutation.SetAuthor(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := wikipageversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WikiPageVersionCreate) check() error {
	if _, ok := _c.mutation.PageSlug(); !ok {
		return &ValidationError{Name: "page_slug", err: errors.New(`ent: missing required field "WikiPageVersion.page_slug"`)}
	}
	if v, ok := _c.mutation.PageSlug(); ok {
		if err := wikipageversion.PageSlugValidator(v); err != nil {
			return &ValidationError{Name: "page_slug", err: fmt.Errorf(`ent: validator failed for field "WikiPageVersion.page_slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "WikiPageVersion.content"`)}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "WikiPageVersion.summary"`)}
	}
	if _, ok := _c.mutation.Author(); !ok {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required field "WikiPageVersion.author"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WikiPageVersion.created_at"`)}
	}
	return nil
}

func (_c *WikiPageVersionCreate) sqlSave(ctx context.Context) (*WikiPageVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WikiPageVersionCreate) createSpec() (*WikiPageVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &WikiPageVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wikipageversion.Table, sqlgraph.NewFieldSpec(wikipageversion.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PageSlug(); ok {
		_spec.SetField(wikipageversion.FieldPageSlug, field.TypeString, value)
		_node.PageSlug = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(wikipageversion.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(wikipageversion.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Author(); ok {
		_spec.SetField(wikipageversion.FieldAuthor, field.TypeString, value)
		_node.Author = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(wikipageversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipageversion.ProjectTable,
			Columns: []string{wikipageversion.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_wiki_versions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WikiPageVersionCreateBulk is the builder for creating many WikiPageVersion entities in bulk.
type WikiPageVersionCreateBulk struct {
	config
	err      error
	builders []*WikiPageVersionCreate
}

// Save creates the WikiPageVersion entities in the database.
func (_c *WikiPageVersionCreateBulk) Save(ctx context.Context) ([]*WikiPageVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WikiPageVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WikiPageVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WikiPageVersionCreateBulk) SaveX(ctx context.Context) []*WikiPageVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WikiPageVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WikiPageVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
