// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/agurrrrr/shepherd/ent/predicate"
	"github.com/agurrrrr/shepherd/ent/project"
	"github.com/agurrrrr/shepherd/ent/wikipage"
)

// WikiPageUpdate is the builder for updating WikiPage entities.
type WikiPageUpdate struct {
	config
	hooks    []Hook
	mutation *WikiPageMutation
}

// Where appends a list predicates to the WikiPageUpdate builder.
func (_u *WikiPageUpdate) Where(ps ...predicate.WikiPage) *WikiPageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *WikiPageUpdate) SetSlug(v string) *WikiPageUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *WikiPageUpdate) SetNillableSlug(v *string) *WikiPageUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *WikiPageUpdate) SetTitle(v string) *WikiPageUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *WikiPageUpdate) SetNillableTitle(v *string) *WikiPageUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *WikiPageUpdate) SetContent(v string) *WikiPageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *WikiPageUpdate) SetNillableContent(v *string) *WikiPageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *WikiPageUpdate) SetCategory(v wikipage.Category) *WikiPageUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *WikiPageUpdate) SetNillableCategory(v *wikipage.Category) *WikiPageUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetAutoGenerated sets the "auto_generated" field.
func (_u *WikiPageUpdate) SetAutoGenerated(v bool) *WikiPageUpdate {
	_u.mutation.SetAutoGenerated(v)
	return _u
}

// SetNillableAutoGenerated sets the "auto_generated" field if the given value is not nil.
func (_u *WikiPageUpdate) SetNillableAutoGenerated(v *bool) *WikiPageUpdate {
	if v != nil {
		_u.SetAutoGenerated(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *WikiPageUpdate) SetTags(v []string) *WikiPageUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *WikiPageUpdate) AppendTags(v []string) *WikiPageUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *WikiPageUpdate) ClearTags() *WikiPageUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetLastUpdatedByTask sets the "last_updated_by_task" field.
func (_u *WikiPageUpdate) SetLastUpdatedByTask(v time.Time) *WikiPageUpdate {
	_u.mutation.SetLastUpdatedByTask(v)
	return _u
}

// SetNillableLastUpdatedByTask sets the "last_updated_by_task" field if the given value is not nil.
func (_u *WikiPageUpdate) SetNillableLastUpdatedByTask(v *time.Time) *WikiPageUpdate {
	if v != nil {
		_u.SetLastUpdatedByTask(*v)
	}
	return _u
}

// ClearLastUpdatedByTask clears the value of the "last_updated_by_task" field.
func (_u *WikiPageUpdate) ClearLastUpdatedByTask() *WikiPageUpdate {
	_u.mutation.ClearLastUpdatedByTask()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WikiPageUpdate) SetUpdatedAt(v time.Time) *WikiPageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *WikiPageUpdate) SetProjectID(id int) *WikiPageUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_u *WikiPageUpdate) SetNillableProjectID(id *int) *WikiPageUpdate {
	if id != nil {
		_u = _u.SetProjectID(*id)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *WikiPageUpdate) SetProject(v *Project) *WikiPageUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the WikiPageMutation object of the builder.
func (_u *WikiPageUpdate) Mutation() *WikiPageMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *WikiPageUpdate) ClearProject() *WikiPageUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WikiPageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WikiPageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WikiPageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WikiPageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WikiPageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wikipage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WikiPageUpdate) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := wikipage.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "WikiPage.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := wikipage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "WikiPage.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := wikipage.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "WikiPage.category": %w`, err)}
		}
	}
	return nil
}

func (_u *WikiPageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wikipage.Table, wikipage.Columns, sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(wikipage.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(wikipage.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(wikipage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(wikipage.FieldCategory, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AutoGenerated(); ok {
		_spec.SetField(wikipage.FieldAutoGenerated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(wikipage.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, wikipage.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(wikipage.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastUpdatedByTask(); ok {
		_spec.SetField(wikipage.FieldLastUpdatedByTask, field.TypeTime, value)
	}
	if _u.mutation.LastUpdatedByTaskCleared() {
		_spec.ClearField(wikipage.FieldLastUpdatedByTask, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wikipage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipage.ProjectTable,
			Columns: []string{wikipage.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipage.ProjectTable,
			Columns: []string{wikipage.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wikipage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WikiPageUpdateOne is the builder for updating a single WikiPage entity.
type WikiPageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WikiPageMutation
}

// SetSlug sets the "slug" field.
func (_u *WikiPageUpdateOne) SetSlug(v string) *WikiPageUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *WikiPageUpdateOne) SetNillableSlug(v *string) *WikiPageUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *WikiPageUpdateOne) SetTitle(v string) *WikiPageUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *WikiPageUpdateOne) SetNillableTitle(v *string) *WikiPageUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *WikiPageUpdateOne) SetContent(v string) *WikiPageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *WikiPageUpdateOne) SetNillableContent(v *string) *WikiPageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *WikiPageUpdateOne) SetCategory(v wikipage.Category) *WikiPageUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *WikiPageUpdateOne) SetNillableCategory(v *wikipage.Category) *WikiPageUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetAutoGenerated sets the "auto_generated" field.
func (_u *WikiPageUpdateOne) SetAutoGenerated(v bool) *WikiPageUpdateOne {
	_u.mutation.SetAutoGenerated(v)
	return _u
}

// SetNillableAutoGenerated sets the "auto_generated" field if the given value is not nil.
func (_u *WikiPageUpdateOne) SetNillableAutoGenerated(v *bool) *WikiPageUpdateOne {
	if v != nil {
		_u.SetAutoGenerated(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *WikiPageUpdateOne) SetTags(v []string) *WikiPageUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *WikiPageUpdateOne) AppendTags(v []string) *WikiPageUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *WikiPageUpdateOne) ClearTags() *WikiPageUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetLastUpdatedByTask sets the "last_updated_by_task" field.
func (_u *WikiPageUpdateOne) SetLastUpdatedByTask(v time.Time) *WikiPageUpdateOne {
	_u.mutation.SetLastUpdatedByTask(v)
	return _u
}

// SetNillableLastUpdatedByTask sets the "last_updated_by_task" field if the given value is not nil.
func (_u *WikiPageUpdateOne) SetNillableLastUpdatedByTask(v *time.Time) *WikiPageUpdateOne {
	if v != nil {
		_u.SetLastUpdatedByTask(*v)
	}
	return _u
}

// ClearLastUpdatedByTask clears the value of the "last_updated_by_task" field.
func (_u *WikiPageUpdateOne) ClearLastUpdatedByTask() *WikiPageUpdateOne {
	_u.mutation.ClearLastUpdatedByTask()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WikiPageUpdateOne) SetUpdatedAt(v time.Time) *WikiPageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *WikiPageUpdateOne) SetProjectID(id int) *WikiPageUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_u *WikiPageUpdateOne) SetNillableProjectID(id *int) *WikiPageUpdateOne {
	if id != nil {
		_u = _u.SetProjectID(*id)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *WikiPageUpdateOne) SetProject(v *Project) *WikiPageUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the WikiPageMutation object of the builder.
func (_u *WikiPageUpdateOne) Mutation() *WikiPageMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *WikiPageUpdateOne) ClearProject() *WikiPageUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the WikiPageUpdate builder.
func (_u *WikiPageUpdateOne) Where(ps ...predicate.WikiPage) *WikiPageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WikiPageUpdateOne) Select(field string, fields ...string) *WikiPageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WikiPage entity.
func (_u *WikiPageUpdateOne) Save(ctx context.Context) (*WikiPage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WikiPageUpdateOne) SaveX(ctx context.Context) *WikiPage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WikiPageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WikiPageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WikiPageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wikipage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WikiPageUpdateOne) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := wikipage.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "WikiPage.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := wikipage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "WikiPage.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := wikipage.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "WikiPage.category": %w`, err)}
		}
	}
	return nil
}

func (_u *WikiPageUpdateOne) sqlSave(ctx context.Context) (_node *WikiPage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wikipage.Table, wikipage.Columns, sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WikiPage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wikipage.FieldID)
		for _, f := range fields {
			if !wikipage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wikipage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(wikipage.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(wikipage.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(wikipage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(wikipage.FieldCategory, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AutoGenerated(); ok {
		_spec.SetField(wikipage.FieldAutoGenerated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(wikipage.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, wikipage.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(wikipage.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastUpdatedByTask(); ok {
		_spec.SetField(wikipage.FieldLastUpdatedByTask, field.TypeTime, value)
	}
	if _u.mutation.LastUpdatedByTaskCleared() {
		_spec.ClearField(wikipage.FieldLastUpdatedByTask, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wikipage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipage.ProjectTable,
			Columns: []string{wikipage.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipage.ProjectTable,
			Columns: []string{wikipage.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WikiPage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wikipage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
