// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agurrrrr/shepherd/ent/predicate"
	"github.com/agurrrrr/shepherd/ent/project"
	"github.com/agurrrrr/shepherd/ent/wikipageversion"
)

// WikiPageVersionUpdate is the builder for updating WikiPageVersion entities.
type WikiPageVersionUpdate struct {
	config
	hooks    []Hook
	mutation *WikiPageVersionMutation
}

// Where appends a list predicates to the WikiPageVersionUpdate builder.
func (_u *WikiPageVersionUpdate) Where(ps ...predicate.WikiPageVersion) *WikiPageVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPageSlug sets the "page_slug" field.
func (_u *WikiPageVersionUpdate) SetPageSlug(v string) *WikiPageVersionUpdate {
	_u.mutation.SetPageSlug(v)
	return _u
}

// SetNillablePageSlug sets the "page_slug" field if the given value is not nil.
func (_u *WikiPageVersionUpdate) SetNillablePageSlug(v *string) *WikiPageVersionUpdate {
	if v != nil {
		_u.SetPageSlug(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *WikiPageVersionUpdate) SetContent(v string) *WikiPageVersionUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *WikiPageVersionUpdate) SetNillableContent(v *string) *WikiPageVersionUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *WikiPageVersionUpdate) SetSummary(v string) *WikiPageVersionUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *WikiPageVersionUpdate) SetNillableSummary(v *string) *WikiPageVersionUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *WikiPageVersionUpdate) SetAuthor(v string) *WikiPageVersionUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *WikiPageVersionUpdate) SetNillableAuthor(v *string) *WikiPageVersionUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *WikiPageVersionUpdate) SetProjectID(id int) *WikiPageVersionUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_u *WikiPageVersionUpdate) SetNillableProjectID(id *int) *WikiPageVersionUpdate {
	if id != nil {
		_u = _u.SetProjectID(*id)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *WikiPageVersionUpdate) SetProject(v *Project) *WikiPageVersionUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the WikiPageVersionMutation object of the builder.
func (_u *WikiPageVersionUpdate) Mutation() *WikiPageVersionMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *WikiPageVersionUpdate) ClearProject() *WikiPageVersionUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WikiPageVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WikiPageVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WikiPageVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WikiPageVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WikiPageVersionUpdate) check() error {
	if v, ok := _u.mutation.PageSlug(); ok {
		if err := wikipageversion.PageSlugValidator(v); err != nil {
			return &ValidationError{Name: "page_slug", err: fmt.Errorf(`ent: validator failed for field "WikiPageVersion.page_slug": %w`, err)}
		}
	}
	return nil
}

func (_u *WikiPageVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wikipageversion.Table, wikipageversion.Columns, sqlgraph.NewFieldSpec(wikipageversion.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PageSlug(); ok {
		_spec.SetField(wikipageversion.FieldPageSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(wikipageversion.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(wikipageversion.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(wikipageversion.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipageversion.ProjectTable,
			Columns: []string{wikipageversion.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipageversion.ProjectTable,
			Columns: []string{wikipageversion.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wikipageversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WikiPageVersionUpdateOne is the builder for updating a single WikiPageVersion entity.
type WikiPageVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WikiPageVersionMutation
}

// SetPageSlug sets the "page_slug" field.
func (_u *WikiPageVersionUpdateOne) SetPageSlug(v string) *WikiPageVersionUpdateOne {
	_u.mutation.SetPageSlug(v)
	return _u
}

// SetNillablePageSlug sets the "page_slug" field if the given value is not nil.
func (_u *WikiPageVersionUpdateOne) SetNillablePageSlug(v *string) *WikiPageVersionUpdateOne {
	if v != nil {
		_u.SetPageSlug(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *WikiPageVersionUpdateOne) SetContent(v string) *WikiPageVersionUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *WikiPageVersionUpdateOne) SetNillableContent(v *string) *WikiPageVersionUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *WikiPageVersionUpdateOne) SetSummary(v string) *WikiPageVersionUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *WikiPageVersionUpdateOne) SetNillableSummary(v *string) *WikiPageVersionUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *WikiPageVersionUpdateOne) SetAuthor(v string) *WikiPageVersionUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *WikiPageVersionUpdateOne) SetNillableAuthor(v *string) *WikiPageVersionUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *WikiPageVersionUpdateOne) SetProjectID(id int) *WikiPageVersionUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_u *WikiPageVersionUpdateOne) SetNillableProjectID(id *int) *WikiPageVersionUpdateOne {
	if id != nil {
		_u = _u.SetProjectID(*id)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *WikiPageVersionUpdateOne) SetProject(v *Project) *WikiPageVersionUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the WikiPageVersionMutation object of the builder.
func (_u *WikiPageVersionUpdateOne) Mutation() *WikiPageVersionMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *WikiPageVersionUpdateOne) ClearProject() *WikiPageVersionUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the WikiPageVersionUpdate builder.
func (_u *WikiPageVersionUpdateOne) Where(ps ...predicate.WikiPageVersion) *WikiPageVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WikiPageVersionUpdateOne) Select(field string, fields ...string) *WikiPageVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WikiPageVersion entity.
func (_u *WikiPageVersionUpdateOne) Save(ctx context.Context) (*WikiPageVersion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WikiPageVersionUpdateOne) SaveX(ctx context.Context) *WikiPageVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WikiPageVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WikiPageVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WikiPageVersionUpdateOne) check() error {
	if v, ok := _u.mutation.PageSlug(); ok {
		if err := wikipageversion.PageSlugValidator(v); err != nil {
			return &ValidationError{Name: "page_slug", err: fmt.Errorf(`ent: validator failed for field "WikiPageVersion.page_slug": %w`, err)}
		}
	}
	return nil
}

func (_u *WikiPageVersionUpdateOne) sqlSave(ctx context.Context) (_node *WikiPageVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wikipageversion.Table, wikipageversion.Columns, sqlgraph.NewFieldSpec(wikipageversion.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WikiPageVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wikipageversion.FieldID)
		for _, f := range fields {
			if !wikipageversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wikipageversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PageSlug(); ok {
		_spec.SetField(wikipageversion.FieldPageSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(wikipageversion.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(wikipageversion.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(wikipageversion.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipageversion.ProjectTable,
			Columns: []string{wikipageversion.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipageversion.ProjectTable,
			Columns: []string{wikipageversion.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WikiPageVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wikipageversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
