// Code generated by ent, DO NOT EDIT.

package wikipage

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the wikipage type in the database.
	Label = "wiki_page"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldAutoGenerated holds the string denoting the auto_generated field in the database.
	FieldAutoGenerated = "auto_generated"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldLastUpdatedByTask holds the string denoting the last_updated_by_task field in the database.
	FieldLastUpdatedByTask = "last_updated_by_task"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// Table holds the table name of the wikipage in the database.
	Table = "wiki_pages"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "wiki_pages"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_wiki_pages"
)

// Columns holds all SQL columns for wikipage fields.
var Columns = []string{
	FieldID,
	FieldSlug,
	FieldTitle,
	FieldContent,
	FieldCategory,
	FieldAutoGenerated,
	FieldTags,
	FieldLastUpdatedByTask,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "wiki_pages"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"project_wiki_pages",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultContent holds the default value on creation for the "content" field.
	DefaultContent string
	// DefaultAutoGenerated holds the default value on creation for the "auto_generated" field.
	DefaultAutoGenerated bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Category defines the type for the "category" enum field.
type Category string

// CategoryCustom is the default value of the Category enum.
const DefaultCategory = CategoryCustom

// Category values.
const (
	CategoryArchitecture    Category = "architecture"
	CategoryPatterns        Category = "patterns"
	CategoryTroubleshooting Category = "troubleshooting"
	CategoryDeployment      Category = "deployment"
	CategoryLessons         Category = "lessons"
	CategoryEntity          Category = "entity"
	CategoryCustom          Category = "custom"
)

func (c Category) String() string {
	return string(c)
}

// CategoryValidator is a validator for the "category" field enum values. It is called by the builders before save.
func CategoryValidator(c Category) error {
	switch c {
	case CategoryArchitecture, CategoryPatterns, CategoryTroubleshooting, CategoryDeployment, CategoryLessons, CategoryEntity, CategoryCustom:
		return nil
	default:
		return fmt.Errorf("wikipage: invalid enum value for category field: %q", c)
	}
}

// OrderOption defines the ordering options for the WikiPage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByAutoGenerated orders the results by the auto_generated field.
func ByAutoGenerated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoGenerated, opts...).ToFunc()
}

// ByLastUpdatedByTask orders the results by the last_updated_by_task field.
func ByLastUpdatedByTask(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUpdatedByTask, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
