// Code generated by ent, DO NOT EDIT.

package schedule

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the schedule type in the database.
	Label = "schedule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPrompt holds the string denoting the prompt field in the database.
	FieldPrompt = "prompt"
	// FieldScheduleType holds the string denoting the schedule_type field in the database.
	FieldScheduleType = "schedule_type"
	// FieldCronExpr holds the string denoting the cron_expr field in the database.
	FieldCronExpr = "cron_expr"
	// FieldIntervalSeconds holds the string denoting the interval_seconds field in the database.
	FieldIntervalSeconds = "interval_seconds"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldLastRun holds the string denoting the last_run field in the database.
	FieldLastRun = "last_run"
	// FieldNextRun holds the string denoting the next_run field in the database.
	FieldNextRun = "next_run"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// Table holds the table name of the schedule in the database.
	Table = "schedules"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "schedules"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_schedules"
)

// Columns holds all SQL columns for schedule fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPrompt,
	FieldScheduleType,
	FieldCronExpr,
	FieldIntervalSeconds,
	FieldEnabled,
	FieldLastRun,
	FieldNextRun,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "schedules"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"project_schedules",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PromptValidator is a validator for the "prompt" field. It is called by the builders before save.
	PromptValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// ScheduleType defines the type for the "schedule_type" enum field.
type ScheduleType string

// ScheduleType values.
const (
	ScheduleTypeCron     ScheduleType = "cron"
	ScheduleTypeInterval ScheduleType = "interval"
)

func (st ScheduleType) String() string {
	return string(st)
}

// ScheduleTypeValidator is a validator for the "schedule_type" field enum values. It is called by the builders before save.
func ScheduleTypeValidator(st ScheduleType) error {
	switch st {
	case ScheduleTypeCron, ScheduleTypeInterval:
		return nil
	default:
		return fmt.Errorf("schedule: invalid enum value for schedule_type field: %q", st)
	}
}

// OrderOption defines the ordering options for the Schedule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPrompt orders the results by the prompt field.
func ByPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrompt, opts...).ToFunc()
}

// ByScheduleType orders the results by the schedule_type field.
func ByScheduleType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScheduleType, opts...).ToFunc()
}

// ByCronExpr orders the results by the cron_expr field.
func ByCronExpr(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCronExpr, opts...).ToFunc()
}

// ByIntervalSeconds orders the results by the interval_seconds field.
func ByIntervalSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntervalSeconds, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByLastRun orders the results by the last_run field.
func ByLastRun(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRun, opts...).ToFunc()
}

// ByNextRun orders the results by the next_run field.
func ByNextRun(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRun, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
