package wiki

import (
	"context"
	"fmt"
	"math"
	"os"
	"strings"
	"time"

	"github.com/agurrrrr/shepherd/ent/project"
	"github.com/agurrrrr/shepherd/ent/wikipage"
	"github.com/agurrrrr/shepherd/internal/db"
)

// WikiIssue represents a lint finding.
type WikiIssue struct {
	Type    string `json:"type"` // "orphan", "stale", "duplicate", "contradiction"
	Slug    string `json:"slug"`
	Message string `json:"message"`
}

// Lint runs health checks on all wiki pages for a project.
func Lint(projectName string) []WikiIssue {
	ctx := context.Background()
	client := db.Client()

	pages, err := client.WikiPage.Query().
		Where(wikipage.HasProjectWith(project.Name(projectName))).
		WithProject().
		All(ctx)
	if err != nil {
		return nil
	}

	if len(pages) == 0 {
		return nil
	}

	var issues []WikiIssue

	// Build a set of referenced slugs from all page contents
	referencedSlugs := make(map[string]bool)
	for _, p := range pages {
		referenced := extractWikiLinks(p.Content)
		for _, ref := range referenced {
			referencedSlugs[ref] = true
		}
	}

	// Check 1: orphan pages (not referenced by any other page)
	for _, p := range pages {
		if len(pages) > 1 && !referencedSlugs[p.Slug] {
			issues = append(issues, WikiIssue{
				Type:    "orphan",
				Slug:    p.Slug,
				Message: fmt.Sprintf("페이지 %q 은 다른 페이지에서 참조되지 않습니다", p.Slug),
			})
		}
	}

	// Check 2: stale pages (not updated for 30+ days)
	threshold := time.Now().AddDate(0, 0, -30)
	for _, p := range pages {
		if p.UpdatedAt.Before(threshold) {
			daysAgo := int(time.Since(p.UpdatedAt).Hours() / 24)
			issues = append(issues, WikiIssue{
				Type:    "stale",
				Slug:    p.Slug,
				Message: fmt.Sprintf("페이지 %q 가 %d일 동안 업데이트되지 않았습니다", p.Slug, daysAgo),
			})
		}
	}

	// Check 3: duplicate content (simple string similarity)
	for i := 0; i < len(pages); i++ {
		for j := i + 1; j < len(pages); j++ {
			sim := contentSimilarity(pages[i].Content, pages[j].Content)
			if sim > 0.85 {
				issues = append(issues, WikiIssue{
					Type:    "duplicate",
					Slug:    pages[i].Slug,
					Message: fmt.Sprintf("페이지 %q 과 %q 의 내용이 %.0f%% 유사합니다 (복사/붙여넣기 확인)", pages[i].Slug, pages[j].Slug, sim*100),
				})
			}
		}
	}

	// Check 4: contradiction (auto_generated page content mismatch with file)
	for _, p := range pages {
		if p.AutoGenerated {
			filePath := pageFilePath(projectName, p.Slug, p.Category)
			if data, err := os.ReadFile(filePath); err == nil {
				_, body, _ := parseFrontmatter(string(data))
				if body != p.Content {
					issues = append(issues, WikiIssue{
						Type:    "contradiction",
						Slug:    p.Slug,
						Message: fmt.Sprintf("페이지 %q 는 auto_generated=true 이지만 파일 시스템의 내용과 DB 내용이 다릅니다", p.Slug),
					})
				}
			}
		}
	}

	return issues
}

// extractWikiLinks extracts wiki page references from markdown content.
// Supports [[slug]] and [[slug|display]] syntax.
func extractWikiLinks(content string) []string {
	var refs []string
	for i := 0; i < len(content); i++ {
		if i+1 < len(content) && content[i] == '[' && content[i+1] == '[' {
			end := strings.Index(content[i+2:], "]")
			if end == -1 {
				continue
			}
			ref := strings.TrimSpace(content[i+2 : i+2+end])
			ref = strings.SplitN(ref, "|", 2)[0]
			ref = strings.TrimSpace(ref)
			if ref != "" {
				refs = append(refs, ref)
			}
			i += 2 + end
		}
	}
	return refs
}

// contentSimilarity calculates similarity between two strings using
// token overlap ratio against the shorter document.
func contentSimilarity(a, b string) float64 {
	if a == b {
		return 1.0
	}
	if a == "" || b == "" {
		return 0.0
	}

	aWords := tokenize(a)
	bWords := tokenize(b)

	if len(aWords) == 0 || len(bWords) == 0 {
		return 0.0
	}

	aSet := make(map[string]int)
	for _, w := range aWords {
		aSet[w]++
	}

	bSet := make(map[string]int)
	for _, w := range bWords {
		bSet[w]++
	}

	intersection := 0
	for w, cnt := range aSet {
		if bCnt, ok := bSet[w]; ok {
			intersection += int(math.Min(float64(cnt), float64(bCnt)))
		}
	}

	minLen := math.Min(float64(len(aWords)), float64(len(bWords)))
	if minLen == 0 {
		return 0.0
	}

	return float64(intersection) / minLen
}

// tokenize splits content into lowercase words for similarity comparison.
func tokenize(content string) []string {
	content = strings.ToLower(content)
	var words []string
	var current strings.Builder
	for _, r := range content {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' || r == '-' {
			current.WriteRune(r)
		} else {
			if current.Len() > 1 {
				words = append(words, current.String())
				current.Reset()
			}
		}
	}
	if current.Len() > 1 {
		words = append(words, current.String())
	}
	return words
}
