package wiki

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/agurrrrr/shepherd/ent"
	"github.com/agurrrrr/shepherd/ent/project"
	"github.com/agurrrrr/shepherd/ent/wikipage"
	"github.com/agurrrrr/shepherd/internal/config"
	"github.com/agurrrrr/shepherd/internal/db"
)

func findProjectByName(projectName string) (*ent.Project, error) {
	ctx := context.Background()
	client := db.Client()

	p, err := client.Project.Query().
		Where(project.Name(projectName)).
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("project %q not found", projectName)
		}
		return nil, fmt.Errorf("failed to query project: %w", err)
	}
	return p, nil
}

func findPageByProjectAndSlug(projectName, slug string) (*ent.WikiPage, error) {
	ctx := context.Background()
	client := db.Client()

	p, err := client.WikiPage.Query().
		Where(
			wikipage.HasProjectWith(project.Name(projectName)),
			wikipage.Slug(slug),
		).
		WithProject().
		Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to query wiki page: %w", err)
	}
	return p, nil
}

// WikiDir returns the wiki directory for a project.
// ~/.shepherd/projects/<project_name>/wiki/
func WikiDir(projectName string) string {
	return filepath.Join(config.GetConfigDir(), "projects", projectName, "wiki")
}

// pageFilePath returns the file path for a wiki page based on its category.
// entity category -> entities/ subdirectory, others -> root wiki dir.
func pageFilePath(projectName string, slug string, category wikipage.Category) string {
	base := WikiDir(projectName)
	if category == wikipage.CategoryEntity {
		return filepath.Join(base, "entities", slug+".md")
	}
	return filepath.Join(base, slug+".md")
}

// CreatePage creates a new wiki page for a project.
func CreatePage(projectName, slug, title, category, content string, tags []string) (*ent.WikiPage, error) {
	ctx := context.Background()
	client := db.Client()

	p, err := findProjectByName(projectName)
	if err != nil {
		return nil, err
	}

	existing, err := findPageByProjectAndSlug(projectName, slug)
	if err != nil {
		return nil, err
	}
	if existing != nil {
		return nil, fmt.Errorf("wiki page %q already exists", slug)
	}

	cat := wikipage.CategoryCustom
	if category != "" {
		cat = wikipage.Category(category)
	}

	wp, err := client.WikiPage.Create().
		SetSlug(slug).
		SetTitle(title).
		SetContent(content).
		SetCategory(cat).
		SetAutoGenerated(true).
		SetTags(tags).
		SetProject(p).
		SetLastUpdatedByTask(time.Now()).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to create wiki page: %w", err)
	}

	_ = SyncToFile(wp, projectName)

	return findPageByProjectAndSlug(projectName, slug)
}

// UpdatePage updates an existing wiki page.
func UpdatePage(projectName, slug, title, content string, tags []string) (*ent.WikiPage, error) {
	ctx := context.Background()
	client := db.Client()

	existing, err := findPageByProjectAndSlug(projectName, slug)
	if err != nil {
		return nil, err
	}
	if existing == nil {
		return nil, fmt.Errorf("wiki page %q not found", slug)
	}

	builder := client.WikiPage.UpdateOneID(existing.ID).
		SetLastUpdatedByTask(time.Now())

	if title != "" {
		builder = builder.SetTitle(title)
	}
	if content != "" {
		builder = builder.SetContent(content)
	}
	builder = builder.SetTags(tags)

	_, err = builder.Save(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, fmt.Errorf("wiki page %q not found", slug)
		}
		return nil, fmt.Errorf("failed to update wiki page: %w", err)
	}

	updated, err := findPageByProjectAndSlug(projectName, slug)
	if err != nil {
		return nil, err
	}
	_ = SyncToFile(updated, projectName)

	return updated, nil
}

// GetPage retrieves a wiki page by project name and slug.
func GetPage(projectName, slug string) (*ent.WikiPage, error) {
	page, err := findPageByProjectAndSlug(projectName, slug)
	if err != nil {
		return nil, err
	}
	if page == nil {
		return nil, fmt.Errorf("wiki page %q not found in project %q", slug, projectName)
	}
	return page, nil
}

// ListPages lists all wiki pages for a project.
func ListPages(projectName string) ([]*ent.WikiPage, error) {
	ctx := context.Background()
	client := db.Client()

	pages, err := client.WikiPage.Query().
		Where(wikipage.HasProjectWith(project.Name(projectName))).
		WithProject().
		Order(ent.Desc(wikipage.FieldUpdatedAt)).
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list wiki pages: %w", err)
	}
	return pages, nil
}

// DeletePage deletes a wiki page.
func DeletePage(projectName, slug string) error {
	page, err := findPageByProjectAndSlug(projectName, slug)
	if err != nil {
		return err
	}
	if page == nil {
		return fmt.Errorf("wiki page %q not found", slug)
	}

	ctx := context.Background()
	client := db.Client()

	err = client.WikiPage.DeleteOneID(page.ID).Exec(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return fmt.Errorf("wiki page %q not found", slug)
		}
		return fmt.Errorf("failed to delete wiki page: %w", err)
	}

	filePath := pageFilePath(projectName, slug, page.Category)
	_ = os.Remove(filePath)
	_ = GenerateIndex(projectName)

	return nil
}

// GetOrCreatePage retrieves an existing page or creates a new one.
func GetOrCreatePage(projectName, slug, title, category string) (*ent.WikiPage, error) {
	existing, err := findPageByProjectAndSlug(projectName, slug)
	if err != nil {
		return nil, err
	}
	if existing != nil {
		return existing, nil
	}

	return CreatePage(projectName, slug, title, category, "", nil)
}

// SyncToFile syncs a wiki page from DB to a markdown file.
func SyncToFile(page *ent.WikiPage, projectName string) error {
	if projectName == "" && page.Edges.Project != nil {
		projectName = page.Edges.Project.Name
	}
	if projectName == "" {
		return fmt.Errorf("project name is required")
	}

	filePath := pageFilePath(projectName, page.Slug, page.Category)
	dir := filepath.Dir(filePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	var tagsStr string
	if len(page.Tags) > 0 {
		tagsStr = strings.Join(page.Tags, ", ")
	}

	var lastUpdatedStr string
	if !page.LastUpdatedByTask.IsZero() {
		lastUpdatedStr = page.LastUpdatedByTask.Format("2006-01-02")
	}

	var frontmatter string
	if tagsStr != "" || lastUpdatedStr != "" {
		fm := fmt.Sprintf("---\ntitle: %s\nslug: %s\ncategory: %s\n", page.Title, page.Slug, page.Category)
		if tagsStr != "" {
			fm += fmt.Sprintf("tags: [%s]\n", tagsStr)
		}
		if lastUpdatedStr != "" {
			fm += fmt.Sprintf("last_updated: %s\n", lastUpdatedStr)
		}
		frontmatter = fm + "---\n"
	}

	content := frontmatter + page.Content
	if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write wiki file: %w", err)
	}

	return nil
}

// parseFrontmatter extracts YAML-like frontmatter and body from a markdown file.
// Returns title, tags, and body content.
func parseFrontmatter(content string) (title, body string, tags []string) {
	trimmed := strings.TrimSpace(content)
	if !strings.HasPrefix(trimmed, "---") {
		return "", trimmed, nil
	}

	endIdx := strings.Index(trimmed[3:], "---")
	if endIdx == -1 {
		return "", trimmed, nil
	}

	fmBlock := trimmed[3 : 3+endIdx]
	body = strings.TrimSpace(trimmed[3+endIdx+3:])

	for _, line := range strings.Split(fmBlock, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "title:") {
			title = strings.TrimSpace(strings.TrimPrefix(line, "title:"))
			title = strings.Trim(title, "\"")
			title = strings.Trim(title, "'")
		} else if strings.HasPrefix(line, "tags:") {
			tagsStr := strings.TrimPrefix(line, "tags:")
			tagsStr = strings.TrimSpace(tagsStr)
			tagsStr = strings.Trim(tagsStr, "[]")
			for _, t := range strings.Split(tagsStr, ",") {
				t = strings.TrimSpace(t)
				if t != "" {
					tags = append(tags, t)
				}
			}
		}
	}

	return title, body, tags
}

// SyncFromDisk syncs changes from disk files to DB.
// Only updates pages where the file is newer than the DB record,
// or where the file content differs from DB content.
func SyncFromDisk(projectName string) error {
	wikiDir := WikiDir(projectName)
	if _, err := os.Stat(wikiDir); os.IsNotExist(err) {
		return nil
	}

	mdFiles, err := collectMarkdownFiles(wikiDir)
	if err != nil {
		return fmt.Errorf("failed to collect markdown files: %w", err)
	}

	for _, mdFile := range mdFiles {
		relPath, _ := filepath.Rel(wikiDir, mdFile)
		relPath = strings.TrimSuffix(relPath, ".md")

		// Skip index.md
		if relPath == "index" {
			continue
		}

		slug := relPath
		isEntity := false
		if strings.HasPrefix(relPath, "entities/") {
			slug = strings.TrimPrefix(relPath, "entities/")
			isEntity = true
		}

		data, err := os.ReadFile(mdFile)
		if err != nil {
			continue
		}

		fileTitle, body, fileTags := parseFrontmatter(string(data))

		existing, err := findPageByProjectAndSlug(projectName, slug)
		if err != nil {
			continue
		}

		if existing != nil {
			if !existing.AutoGenerated && existing.Content == body {
				continue
			}

			if existing.AutoGenerated && existing.Content == body {
				continue
			}

			if existing.AutoGenerated {
				info, statErr := os.Stat(mdFile)
				if statErr == nil {
					fileModTime := info.ModTime()
					dbTime := existing.UpdatedAt
					if !dbTime.IsZero() && fileModTime.Before(dbTime) {
						continue
					}
				}
			}

			if fileTitle == "" {
				fileTitle = existing.Title
			}

			ctx := context.Background()
			client := db.Client()

			_, updateErr := client.WikiPage.UpdateOneID(existing.ID).
				SetTitle(fileTitle).
				SetContent(body).
				SetAutoGenerated(false).
				SetTags(fileTags).
				Save(ctx)
			if updateErr != nil {
				continue
			}
		} else {
			ctx := context.Background()
			client := db.Client()

			p, projErr := findProjectByName(projectName)
			if projErr != nil {
				continue
			}

			if fileTitle == "" {
				fileTitle = strings.ReplaceAll(slug, "_", " ")
				fileTitle = strings.Title(fileTitle)
			}

			cat := wikipage.CategoryCustom
			if isEntity {
				cat = wikipage.CategoryEntity
			}

			_, createErr := client.WikiPage.Create().
				SetSlug(slug).
				SetTitle(fileTitle).
				SetContent(body).
				SetCategory(cat).
				SetAutoGenerated(false).
				SetTags(fileTags).
				SetProject(p).
				SetLastUpdatedByTask(time.Now()).
				Save(ctx)
			if createErr != nil {
				continue
			}
		}
	}

	return nil
}

// collectMarkdownFiles recursively collects .md files from the wiki directory.
func collectMarkdownFiles(dir string) ([]string, error) {
	var files []string
	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(strings.ToLower(path), ".md") {
			files = append(files, path)
		}
		return nil
	})
	return files, err
}

// SyncPageBidirectional syncs a single page between DB and file system.
// For auto_generated=true: DB is the source of truth, file is overwritten if DB is newer.
// For auto_generated=false: File is the source of truth, DB is updated if file has changed.
func SyncPageBidirectional(projectName, slug string) error {
	page, err := findPageByProjectAndSlug(projectName, slug)
	if err != nil {
		return err
	}

	if page == nil {
		mdFile := filepath.Join(WikiDir(projectName), slug+".md")
		if _, statErr := os.Stat(mdFile); statErr == nil {
			return SyncFromDisk(projectName)
		}
		return nil
	}

	filePath := pageFilePath(projectName, page.Slug, page.Category)

	if page.AutoGenerated {
		dbTime := page.UpdatedAt
		if dbTime.IsZero() {
			_ = SyncToFile(page, projectName)
			return nil
		}

		fileInfo, statErr := os.Stat(filePath)
		if statErr != nil || fileInfo.ModTime().Before(dbTime) {
			_ = SyncToFile(page, projectName)
			return nil
		}

		data, readErr := os.ReadFile(filePath)
		if readErr == nil {
			_, body, _ := parseFrontmatter(string(data))
			if body != page.Content {
				ctx := context.Background()
				client := db.Client()
				_, _ = client.WikiPage.UpdateOneID(page.ID).
					SetContent(body).
					SetAutoGenerated(false).
					Save(ctx)
			}
		}
	} else {
		data, readErr := os.ReadFile(filePath)
		if readErr != nil {
			_ = SyncToFile(page, projectName)
			return nil
		}

		fileTitle, body, fileTags := parseFrontmatter(string(data))

		ctx := context.Background()
		client := db.Client()

		if fileTitle != "" {
			page.Title = fileTitle
		}

		_, err = client.WikiPage.UpdateOneID(page.ID).
			SetTitle(page.Title).
			SetContent(body).
			SetTags(fileTags).
			Save(ctx)
		if err != nil {
			return fmt.Errorf("failed to sync page from disk: %w", err)
		}
	}

	return nil
}

// GenerateIndex creates or updates the index.md file for a project.
func GenerateIndex(projectName string) error {
	pages, err := ListPages(projectName)
	if err != nil {
		return err
	}

	if len(pages) == 0 {
		return nil
	}

	sort.Slice(pages, func(i, j int) bool {
		return pages[i].Slug < pages[j].Slug
	})

	wikiDir := WikiDir(projectName)
	if err := os.MkdirAll(wikiDir, 0755); err != nil {
		return fmt.Errorf("failed to create wiki directory: %w", err)
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# %s Wiki\n\n", projectName))
	sb.WriteString("> 자동 생성 — 수동 편집하지 마세요.\n\n")
	sb.WriteString("## 페이지 목록\n\n")
	sb.WriteString("| 슬러그 | 제목 | 카테고리 | 태그 | 마지막 수정 |\n")
	sb.WriteString("|--------|------|----------|------|-------------|\n")

	for _, p := range pages {
		tagsStr := strings.Join(p.Tags, ", ")
		var updatedAtStr string
		if !p.UpdatedAt.IsZero() {
			updatedAtStr = p.UpdatedAt.Format("2006-01-02")
		}

		sb.WriteString(fmt.Sprintf(
			"| %s | %s | %s | %s | %s |\n",
			p.Slug, p.Title, p.Category, tagsStr, updatedAtStr,
		))
	}

	indexPath := filepath.Join(wikiDir, "index.md")
	return os.WriteFile(indexPath, []byte(sb.String()), 0644)
}
