// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BrowserSession is the predicate function for browsersession builders.
type BrowserSession func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Schedule is the predicate function for schedule builders.
type Schedule func(*sql.Selector)

// Sheep is the predicate function for sheep builders.
type Sheep func(*sql.Selector)

// SheepName is the predicate function for sheepname builders.
type SheepName func(*sql.Selector)

// Skill is the predicate function for skill builders.
type Skill func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
